### ISSUE TITLE
Why put effort into cannon.js?

### ISSUE THREAD

**Issue by schteppe** [schteppe/cannon.js#1]
Hi dear followers of cannon.js,

I was thinking about making a proposal to put some extra resources on cannon.js at my lab. We have the knowledge to make a fully featured 3D physics engine in here, but the guys at my lab think that such investment isn't worth doing. All they think of is performance (which is fully understandable when working with real time simulation) and therefore they see JavaScript as a bad deal. C++ has been _the_ language from the very start.

So I was wondering how you guys would explain the Need, Approach, Benefit and Competition to present this "innovation", making the best impression possible. I already have some ideas myself but I would like to hear yours too.

Thanks,
Stefan

**Comment by yiakwy** [comment]
@mrdoob @schteppe @chandlerprall It seems that cannon.js does not support webworker while phsijs does. And also cannon.js does not support well in es6. With asyn, await, we will definitely use webworker happily.

This will be good for real-time physics planning. For example, in tween.js we use following way to schedule animation continuousely based on  obstacles' peception from pseudo camera:

```js

update(scene, delta) {
if (this.fixedRate) {
updateFixRate(scene, delta)
}

if (!this.isStarted()) {
 beforeStart()
}

cruise() {
.... bla bla bla
let tweenjob = this.execute("create", param)
this.bufferArray.push(tweenjob)
}

async this._completeTweenCb() {
let tween
if (this.bufferArray.length > 0) {
  let tweenjob = this.bufferArray.shift()
  tween = this.execute("fetch", tweenjob.id)

} else {
  tween = await this.createAndFetch()

}
  this.tween.stop()
  this.tween = tween
  this.tween.start()
}

```

We can use the similar structure for cannon.js! Which means at least we could have two different clock cycles and the work will help us with planning.
