### ISSUE TITLE
object stopped , three.js + cannon.js 

### ISSUE THREAD

**Issue by metmet** [schteppe/cannon.js#106]
I have a obj falling,
i need the property like. getobjStoped, now i use in reader 

var runPhysics = true;
function updatePhysics() {
    if (runPhysics){
    // Step the physics world
    world.step(timeStep);
    for ( var i = 0, l = threeDiceArray.length; i < l; i ++ ) {
    var threeDice   = threeDiceArray[ i ];
    var cannonDice  = cannonDiceArray[ i ];
    console.log("Entro sono uguali a["+a+"]");
    if (oldValue == (cannonDice.position.y+"").substring(0,4) ){
        if (a == 10 ){
        runPhysics = false;
        }else{
        a++;
        }
        }else{
        console.log("Entro sono !=!=!= a["+a+"]");
        a=0;
    }
        // Copy coordinates from Cannon.js to Three.js
        cannonDice.position.copy(threeDice.position);
        cannonDice.quaternion.copy(threeDice.quaternion);

```
    oldValue = (cannonDice.position.y+"").substring(0,4);
}
```

}

i calculate, when the y coordinate for 10 loops dont change the value,
but this solution is dictated by a night to programing,
i think there should be a more clean solution.

thank in advance ,
and thank for cannon.js is very util .

Matteo

**Comment by kalnode** [comment]
> .norm()

What is `.norm()`? Was it a helper previously available?
