### ISSUE TITLE
Scaling a body at runtime?

### ISSUE THREAD

**Issue by oosmoxiecode** [schteppe/cannon.js#117]
Hi!
Is it possible to scale a body dynamically at runtime?

I tried something like this, trying to scale a box:

``` html
body.shape.halfExtents.x = scale;
body.shape.halfExtents.y = scale;
body.shape.halfExtents.z = scale;

body.shape.boundingSphereRadiusNeedsUpdate = true;
```

But that does not look right, I think.

**Comment by bnolan** [comment]
Is is possible to scale spheres into an ellipsoid? I'm doing spheres in scenevr, and I guess I'll tell people not to make ellipsoids :D

**Comment by schteppe** [comment]
Nope. You can only set the radius of the sphere. There's no scale in cannon (except for the local scaling in the Trimesh class).

There are other clever tricks to sort of match the scale between graphics and physics though. Fire up Unity and try scaling a sphere collider into an ellipsoid. You'll see that it does not work, but Unity will still match the sphere radius to cover the ellipsoid :)
