### ISSUE TITLE
y/z axis mismatch

### ISSUE THREAD

**Issue by pyrotechnick** [schteppe/cannon.js#12]
I've noticed you're using values like `0, 0, -10` and `0, 0, -9.81` where gravity is modelled by a negative z value.

In OpenGL/WebGL (including three.js) +y is up with +z pointing out of the screen (right handed).

This is just a heads-up since it doesn't seem to be effecting the demos. I assume your entire scene is rotated on the side from physics to graphics making the scene appear correct.

You may want to consider switching to the more conventional X-left/right, Y-up/down, Z-in/out right-handed coordinate system.

**Comment by duhaime** [comment]
For others who want to use the THREE.js default coordinate orientation (x plane runs left-right, y plane runs up-down, z plane runs near-far) you can rotate the default floor (and thereby add a ground toward which all objects fall) by using a slight twist on @sole's comment:

`planeBody.quaternion.setFromAxisAngle(new CANNON.Vec3(1,0,0), -Math.PI/2)`

where `planeBody` is the body you want to use as your floor. This rotates the `planeBody` 90 degrees on the X axis, which twists it from a plane that runs along the up-down axis to one that is perpendicular to that axis, which prevents things from falling through the floor.

**Comment by duhaime** [comment]
p.s. @pyrotechnick @schteppe I think this issue can be closed

**Comment by seidtgeist** [comment]
It’s been a good issue, thanks everyone, I enjoyed getting email notifications over the years 😄

**Comment by ClayCooperLA** [comment]
in THREE.js set the default up to Z, `THREE.Object3D.DefaultUp.set(0, 0, 1);`
https://stackoverflow.com/questions/8272297/three-js-rotate-projection-so-that-the-y-axis-becomes-the-z-axis
