### ISSUE TITLE
Dynamically changing shape & mass properties

### ISSUE THREAD

**Issue by schteppe** [schteppe/cannon.js#122]
Currently, to change the shape dimensions of for example a box, this code is needed.
```js
boxShape.halfExtents.set(1,2,3);
boxShape.updateConvexPolyhedronRepresentation();
boxShape.computeBoundingSphereRadius();
boxBody.computeAABB();
```
Furthermore, to update the mass properties becomes:
```js
boxBody.mass = boxBody.invMass = 0;
boxShape.calculateLocalInertia(newMass,boxBody.inertia);
boxBody.invInertia.set(boxBody.inertia.x>0 ? 1.0/boxBody.inertia.x : 0,
                       boxBody.inertia.y>0 ? 1.0/boxBody.inertia.y : 0,
                       boxBody.inertia.z>0 ? 1.0/boxBody.inertia.z : 0);
boxBody.updateInertiaWorld(true);
```
Don't think this is very intuitive. Maybe add methods for updating mass properties and shape data?

**Comment by JamesHagerman** [comment]
@schteppe Is changing mass this way still the case?

I'm trying to "freeze" objects in my scene by setting their mass to 0 and their velocity vector to 0,0,0 but the objects are still moving when a dynamic object on the end of a springs hits the "frozen" object.

Maybe trying to freeze the object by setting 0 mass is the wrong way?

**Comment by schteppe** [comment]
Body.prototype.updateMassProperties() was added. Let me know if it doesn't do its job.

You can freeze an object in a few ways. Setting zero mass is probably one of the simplest.

**Comment by JamesHagerman** [comment]
Sorry for the delayed response!

So, I also tested this in demo/spring.html. I used a simple timeout to try freezing the boxBody after a few seconds. I had to set the invMass to 0 as well as zero out the linear and angular velocities.

I'm not sure if this is what you intended but that invMass is a little weird :)

```
window.setTimeout(function() {
    boxBody.mass = 0;
    boxBody.invMass = 0;
    boxBody.updateMassProperties();
    boxBody.velocity.set(0,0,0); // Had to add this
    boxBody.angularVelocity.set(0,0,0);
}, 3000);
```

With that, I was able to freeze the object entirely.

**Comment by schteppe** [comment]
Cool! Then it works :)

One might think that the velocity should be set to zero automatically when setting mass to zero. But there's also the case for kinematic bodies, which also have zero mass but not necessarily zero velocity... Manual velocity update is probably the way to go.

**Comment by JamesHagerman** [comment]
Thank you!!

**Comment by mikhuang** [comment]
FYI, `body.type` also needs to be `Body.DYNAMIC` in order to allow physics simulation. I had issues when I started a body with 0 mass and then tried to add mass later (using cannon through aframe-extras) until I manually set body.type
