### ISSUE TITLE
Efficiency of Ray intersections

### ISSUE THREAD

**Issue by willyvvu** [schteppe/cannon.js#129]
I know, this part of the issue should probably belong in StackOverflow.

I was testing the waters for a racing game with cannon.js. The vehicles would be hovering above the ground, and in order to do so, the vehicle has to know how far the ground is beneath it within a short distance.

I was hoping that a physics engine would provide faster collision/ray intersection than native THREE.js. However, I noticed that the ray intersection code still looped through each object to check intersections with them.
https://github.com/schteppe/cannon.js/blob/master/src/collision/Ray.js#L178-L181

Can the efficiency of the ray casting be improved by the use of techinques similar to Broadphase or AABB?
Or, is it possible to use a (hopefully faster) alternative to raycasting, such as somehow parenting a non-colliding "ghost" `CANNON.RigidBody` to the vehicle's `CANNON.RigidBody` and reading the detected collisions from the "ghost"? Alternatively, could I connect a "probe" `CANNON.RigidBody` to the vehicle's `CANNON RigidBody` and use a spring constraint?

**Comment by harraps** [comment]
I would like to check the intersection of a ray with only one bodies. I saw that there is a Ray.intersectBodies( bodies, result ) but I don't understand why I can't get it to work...
How should I use this method ?
