### ISSUE TITLE
applyImpulse() in local coordinates

### ISSUE THREAD

**Issue by zlsa** [schteppe/cannon.js#140]
Is there a way to use `applyForce(...)` and `applyImpulse(...)` in the body's local coordinate system?

**Comment by DelvarWorld** [comment]
I'm super confused about how these work. I'm doing something like this:

playerBody.applyLocalImpulse( new CANNON.Vec3( -200, 0, 0 ), new CANNON.Vec3( 0, 0, 0 ) );

And this *only* affects my player if the absolute player body `position.x` is less than zero. I would expect this to affect my player regardless of position?

**Comment by lazd** [comment]
@DelvarWorld here's how I use it, hope that helps! https://github.com/satellite-game/Satellite-Mobile/blob/88b401047963cf9a1bd0e4fd72af82bea3ca0e95/client/game/classes/s.Controls.js#L85-L103
