### ISSUE TITLE
Create CANNON.RigidBody from THREE.Mesh or THREE.Geometry

### ISSUE THREAD

**Issue by rgajrawala** [schteppe/cannon.js#144]
I am creating a `THREE.Mesh` object using a `THREE.JSONLoader` object like so:

```
// Create castle.
loader.load('/Meshes/CastleTower.js', function(geometry, materials) {
    var tmp_material = new THREE.MeshLambertMaterial();
    THREE.ColorUtils.adjustHSV(tmp_material.color, 0, 0, 0.9);

    var castle = new THREE.Mesh(geometry, tmp_material);
    castle.scale.set(0.2, 0.2, 0.2);
    castle.rotation.setX(-Math.PI/2);
    scene.add(castle);
});
```

Is it possible to create a `CANNON.RigidBody` from the `THREE.Mesh` (`var castle`) or `THREE.Geometry` (`var geometry`) object?

StackOveflow question is [here](http://stackoverflow.com/questions/24543722/create-cannon-rigidbody-from-three-mesh-or-three-geometry).

**Comment by rgajrawala** [comment]
@schteppe Based off [this answer](http://stackoverflow.com/questions/24543722/create-cannon-rigidbody-from-three-mesh-or-three-geometry/#24654621) on the StackOverflow question, I found out that if I use my `.obj` file to create a `.js` file with [this format](http://schteppe.github.io/cannon.js/demos/js/bunny.js), I can use `CANNON.ConvexPolyhedron`s to create a `CANNON.Compound` object.

**Comment by justinlm** [comment]
@usandfriends  how do you create a .js file with a .obj ? thx
