### ISSUE TITLE
Linear damping by axis?

### ISSUE THREAD

**Issue by Ranzear** [schteppe/cannon.js#151]
It looks like body.linearDamping is omnidirectional. I think it was Physi.js and Bullet/Ammo that provided X, Y, and Z damping values, but that library combo is a can of worms when involving node.js.

Say I have a sled on a slope and want it to slide forward and back but not side to side. Is the only current solution to pull out vectors and apply opposing impulses or velocities myself?

It looks like this goes all the way back to #19, with chandlerprall in the conversation no less.

Or maybe I'm misunderstanding and the Vec3 damping that Bullet/Ammo uses is worldspace. Damping by object axis would still be useful for something like a feather or a character in a space with an arbitrary 'down' direction.

Friction is the same conundrum, but my real application is a hovering vehicle, hence damping instead.

**Comment by JamesHagerman** [comment]
I am also looking for this functionality. Moving to a 2D engine is not an option in my case.

As far as I can understand, the callbacks are somehow supposed to be able to implement something such as z-damping (to force the physics world into being 2D?) but I don't understand exactly how preStep() or postStep() would help.

The jsdoc for preStep() says:
```
Dispatched before the world steps forward in time.
```

and your notes in #19 say (effectively):
```
preStep() happens after gravity and contact forces are accumulated
```

So, if I want to place a z-axis position constraint on a bunch of spheres springing towards a center point, how is any kind of damping in preStep() going to help? The calculations are already done and by the time preStep() gets called, I won't have the old z-positions to do damping...

Or maybe I'm confused about how this all works...

Honestly, I'll build a z-axis constraint demo along with documentation and give you a pull request if I can figure this out...

**Comment by schteppe** [comment]
Actually, you can use ```body.linearFactor``` now! Just put a zero on the z component and you have a motion in the xy plane.

```js
new CANNON.Body({ ... linearFactor: new CANNON.Vec3(1,1,0) ... });
```

**Comment by JamesHagerman** [comment]
Hey @schteppe, Thanks for the fast reply!

I just tried setting this on the objects in my scene and it looks like the CANNON.Spring() does not follow that option... or somehow it's being overridden.

Specifically, that option is set on the moveable object at one end of a CANNON.Spring(). The non-moving object is located at 0,0,0.

- When I move the moveable object to 1,0,0 it stays at z=0 and springs back to 0,0,0
- When I move the moveable object to 0,1,0 it stays at z=0 and springs back to 0,0,0
- When I move it again to 1,0,1, the body doesn't stay at z=1 but springs back as if the constraint were not there at all.

Any chance the spring is acting differently than expected?

**Comment by schteppe** [comment]
Np! Actually I think you just found a bug in linearFactor. Must have forgotten to apply it to normal forces in addition to constraint forces. Will fix when there's time.

**Comment by JamesHagerman** [comment]
Awesome! Thank you!

**Comment by schteppe** [comment]
Ok, so I tested this locally in the spring demo (demos/spring.html). LinearFactor seems to work fine, at least on the latest build. Which version are you running?

I added a fix for angularFactor. I noticed that angularFactor doesn't get applied to torques... not related to your problem but still :+1:  https://github.com/schteppe/cannon.js/commit/022e8ba53fa83abf0ad8a0e4fd08623123838a17

**Comment by JamesHagerman** [comment]
Ah, but spring.html places the box on the x,z plane by default:

```
line 45: boxBody.position.set(-size, 0, -size);
```

If you place it at -size, -size, -size it moves on all three axes. If you add the linearFactor parameter, it STILL moves in all three axes!

I found the same situation: If all bodies start ON a plane, it will stay on that plane. But if they start off that plane, the linearFactor constraint doesn't work.

I'm on v0.6.2 by the way.

Thanks for looking into this, and thanks for the help!

**Comment by JamesHagerman** [comment]
Another option would be to just move the sphereBody:

```
sphereBody.position.set(0,1,0);
```

**Comment by schteppe** [comment]
On latest master build, I set: 

```js
boxBody = new CANNON.Body({
    mass: 5,
    linearFactor: new CANNON.Vec3(0,0,0),
    angularFactor: new CANNON.Vec3(0,0,0)
});
```

And I get no movement at all, no matter where the sphere or box are.

**Comment by JamesHagerman** [comment]
Hmm okay. I guess I'll try master. How often do you tag releases?

**Comment by schteppe** [comment]
Cool! Try master and if its OK I'll tag and release asap :)

**Comment by JamesHagerman** [comment]
Weird... I've triple checked that I'm on the current master, set the exact same parameters on lines 40-44 in demos/spring.html and it's not locking the object.

I've tested this under chrome and firefox's latest versions.

Any ideas what might be different?

**Comment by schteppe** [comment]
Did you build? Will recheck my setup too..

**Comment by JamesHagerman** [comment]
Gah! I didn't build. I'll try it again!

**Comment by JamesHagerman** [comment]
The build worked! Thank you so much!

**Comment by DelvarWorld** [comment]
When I use something like

                linearFactor: new CANNON.Vec3( 1, 0, 1 ),
                angularFactor: new CANNON.Vec3( 1, 0, 1 )

to constrain to x and z axis, I get some weird behaviors. My boxes will "stick" in the air and stop responding to gravity. They also behave strangely when forces are applied. I'm making a top-down 2.5d game and need to constrain all physics to the plane of the camera, basically. The only thing I've found that works moderately well is adding a big invisible plane on top of everything to trap it.
