### ISSUE TITLE
Box and heightfield do not collide ?

### ISSUE THREAD

**Issue by synth2014** [schteppe/cannon.js#170]
Sample here http://synth2014.github.io/Age-of-Steam/engg/HeightfieldTest.html

It seems placing the box well within the heightfield works. But at the edge of the heightfield it will fail.

Also this seems to happen along the y-axis only. Something is not uniform.

**Comment by synth2014** [comment]
It seems that the heightfield is shorter in the y direction by 1 unit !

**Comment by schteppe** [comment]
OK, probably a mistake from my side. Until fixed, I guess you could make the heightfield a bit bigger.

**Comment by oxyflour** [comment]
Same issue here. For me, a quick solution is to extend the array at both ends
```
a.unshift(a[0])
a.push(a[a.length - 1])
```

Looking forward to your fix on it : )
