### ISSUE TITLE
getConvexTrianglePillar() returning NaN

### ISSUE THREAD

**Issue by synth2014** [schteppe/cannon.js#171]
Hi,

I am trying a simple heightfield which is a 4 by 4 grid with height uniformly 0.1. I am trying to draw it with:

                        hfshape.getConvexTrianglePillar(xi, yi, k===0);
                        v0.copy(hfshape.pillarConvex.vertices[0]);
                        v1.copy(hfshape.pillarConvex.vertices[1]);
                        v2.copy(hfshape.pillarConvex.vertices[2]);
                        v0.vadd(hfshape.pillarOffset, v0);
                        v1.vadd(hfshape.pillarOffset, v1);
                        v2.vadd(hfshape.pillarOffset, v2);

This is the same code as in the CannonDemo.js file which converts a heightfield shape to a mesh - shape2mesh() function.

I see that the vertices have z = NaN sometimes !

**Comment by schteppe** [comment]
Really? Do you have working code for reproducing this?

**Comment by synth2014** [comment]
Yes of course. Here you go:

http://synth2014.github.io/Age-of-Steam/babylon/HeightmapTest.html

See :

            var heights = new Array(size);
            for (var i = 0; i < size+1; i++) {
                heights[i] = new Array(size+1);
            }

            for (var i = 0; i < size ; i++) {
                for (var j = 0; j < size+1; j++) {
                    if (j == size) {
                        heights[i][j] = 0.1;
                        continue;
                    }
                    heights[j][size-1-i] = matrix[i][j]; // transpose and mirror columns
                }
            }

            // HeightField
         
            var hfbody = ground.setPhysicsState({
                impostor: BABYLON.PhysicsEngine.HeightFieldImpostor,
                heights: heights /*matrix*/,
                position: new BABYLON.Vector3(-((size-1)/2), 0, -((size-1)/2))
            });

            // Draw the heightfield using babylon

            
            var hfshape = hfbody.shapes[0];

            var v0 = new CANNON.Vec3();
            var v1 = new CANNON.Vec3();
            var v2 = new CANNON.Vec3();
            for (var xi = 0; xi < hfshape.data.length - 1; xi++) {
                for (var yi = 0; yi < hfshape.data[xi].length - 1; yi++) {
                    for (var k = 0; k < 2; k++) {
                        hfshape.getConvexTrianglePillar(xi, yi, k===0);
                        v0.copy(hfshape.pillarConvex.vertices[0]);
                        v1.copy(hfshape.pillarConvex.vertices[1]);
                        v2.copy(hfshape.pillarConvex.vertices[2]);
                        v0.vadd(hfshape.pillarOffset, v0);
                        v1.vadd(hfshape.pillarOffset, v1);
                        v2.vadd(hfshape.pillarOffset, v2);
                        
                        v0.vadd(hfbody.position, v0);
                        v1.vadd(hfbody.position, v1);
                        v2.vadd(hfbody.position, v2);
                        
                        console.log("v1(" + v1.x + "," + v1.y + "," + v1.z + ")");
                        console.log("v2(" + v2.x + "," + v2.y + "," + v2.z + ")");
                        
                        if (isNaN(v1.z) || isNaN(v2.z)) {
                            continue;
                        }
                            
                        console.log("v1(" + v1.x + "," + v1.y + "," + v1.z + ")");
                        console.log("v2(" + v2.x + "," + v2.y + "," + v2.z + ")");
                        
                        var hfLine = BABYLON.Mesh.CreateLines("hfLine", [
                            new BABYLON.Vector3(v0.x, v0.z, v0.y),
                            new BABYLON.Vector3(v1.x, v1.z, v1.y)
                        ], scene)
                        hfLine.color = new BABYLON.Color3(1, 1, 0);
                        
                      /*  hfLine = BABYLON.Mesh.CreateLines("hfLine", [
                            new BABYLON.Vector3(v1.x, v1.z, v1.y),
                            new BABYLON.Vector3(v2.x, v2.z, v2.y)
                        ], scene)
                        hfLine.color = new BABYLON.Color3(1, 1, 1);*/
                        
                        hfLine = BABYLON.Mesh.CreateLines("hfLine", [
                            new BABYLON.Vector3(v2.x, v2.z, v2.y),
                            new BABYLON.Vector3(v0.x, v0.z, v0.y)
                        ], scene)
                        hfLine.color = new BABYLON.Color3(1, 1, 0);

                      /*  geometry.vertices.push(
                            new THREE.Vector3(v0.x, v0.y, v0.z),
                            new THREE.Vector3(v1.x, v1.y, v1.z),
                            new THREE.Vector3(v2.x, v2.y, v2.z)
                        );
                        */
                    }
                }
            }

**Comment by schteppe** [comment]
Your "heights" array contains an empty row. That's why.
