### ISSUE TITLE
Mesh geometry and Trimesh

### ISSUE THREAD

**Issue by recoshet** [schteppe/cannon.js#174]
Hi,

I'm trying to use the geometry of the object MESH to Trimesh.
Example: http://naviris.ru/3D2/trimesh.html
But I'm doing something wrong, and so the object Trimesh not displayed on the scene.

To transform a mesh object to Convex polyhedron I did. Tell me how to properly handle geometry for loading it trimesh. 
I saw https://vine.co/v/Ov0ljB6hiPM

**Comment by recoshet** [comment]
Able to run! Not properly assembled array.

sorry

**Comment by schteppe** [comment]
I'm happy you figured it out. And any future feedback you have is very much welcome!
