### ISSUE TITLE
Easy performance improvements

### ISSUE THREAD

**Issue by kirilledelman** [schteppe/cannon.js#177]
While looking for a way to detect when two objects stop colliding (instead of just the initial first collision) In `World.prototype.internalStep` function I found some potential performance bottlenecks:

```js
// Now we know that i and j are in contact. Set collision matrix state
this.collisionMatrix.set(bi, bj, true);

if (this.collisionMatrix.get(bi, bj) !== this.collisionMatrixPrevious.get(bi, bj)) { ...
```

We just set bi / bj to `true` - why call a matrix lookup, if we already know its value.

Then, in the `// Invoke pre-step callbacks` we loop over every body to invoke `.preStep`, and then loop over them again to apply velocity, and then loop over them again to invoke `.postStep`, and then loop over them again to call `sleepTick`. All these could be combined into a single loop.

With large numbers of bodies the performance penalty can be quite severe in this function.

**Comment by schteppe** [comment]
Thanks for the heads-up!
The first one is an easy fix.
The body preStep and postStep callbacks should probably be removed - I don't see why they are needed when there's the same events in the ```World```. (But if I were to keep them, I'd switch to event dispatching instead - makes the API more uniform).

Not sure if I'd put the sleepTick in the same bodies-loop as postStep though - what if the user fiddles with other body sleep states in a .postStep callback, or sets the velocity of a body in a body ```sleep``` event (that is dispatched by .sleepTick())? No, they have to be in separate loops to guarantee a predictable state inside the callbacks.
