### ISSUE TITLE
Heightfield.getRectMinMax() issue

### ISSUE THREAD

**Issue by oxyflour** [schteppe/cannon.js#180]
Hi. Please have a look at the demo first
http://jsfiddle.net/9khtzn4y/

The Heightfield is created with a simple matrix,
```
var matrix = [
    [-0.1, 0],
    [0,  0.0],
]
```
but fails to collide with the spheres. I debugged and found something in the Heightfield.getRectMinMax function. The problem is that iMaxX & iMaxY should be covered in the loop because they have been clamped in previous codes.

I've commit a fix for this, and would create a PR if you think that's OK : )
https://github.com/oxyflour/cannon.js/commit/8a9e51e9695c88d3976b45ef22e05a1831e122c4

**Comment by schteppe** [comment]
I see, nice! Did you test this for other shapes? When the shape is just outside the field?

**Comment by oxyflour** [comment]
I've tested some objects outside the heightfield, and it looks fine.

(before fix) http://jsfiddle.net/9khtzn4y/1/
![f1](https://cloud.githubusercontent.com/assets/1967664/6123993/2898b6e8-b144-11e4-8f2d-cc1f04372143.PNG)

(after fix) http://jsfiddle.net/9khtzn4y/2/
![f2](https://cloud.githubusercontent.com/assets/1967664/6124102/68593f68-b145-11e4-86fd-eee585512d88.PNG)

And results of the following shapes are OK.
(box) http://jsfiddle.net/9khtzn4y/3/
(cylinder) http://jsfiddle.net/9khtzn4y/4/
(convex polyhedron) http://jsfiddle.net/9khtzn4y/5/
(particle) not implemented yet, right?
Note that without this fix, the cylinders will keep dancing on the heightfield lol.

ps: PR is ready
https://github.com/schteppe/cannon.js/pull/181
