### ISSUE TITLE
Collision between two bodies with multiple shapes (explosion bug?)

### ISSUE THREAD

**Issue by ndeineko** [schteppe/cannon.js#182]
Hi, 

First, i want to thanks you for this great project!

I am trying to make a collision between 2 bodies (both with multiple spheres), but the result is not what i expected.

Am I doing something wrong, or is it an issue?

Could you please have a look?

Just go here: http://schteppe.github.io/cannon.js/demos/compound.html , paste this in the console and select the "Sphere2" demo:
````
demo.addScene("Spheres2",function(){
          var world = setupWorld(demo);
          world.gravity.z=-.02;
          var mass = 10;
          var body = new CANNON.Body({ mass: mass });
          body.velocity.x=.4;
          var body2 = new CANNON.Body({ mass: mass });
          body2.velocity.x=-.4;
          var sphereShape = new CANNON.Sphere(1);

          body.addShape(sphereShape, new CANNON.Vec3( 4, 0,-2));
          body.addShape(sphereShape, new CANNON.Vec3( 4, 0, 2));
          body2.addShape(sphereShape, new CANNON.Vec3( 4, 0,-2));
          body2.addShape(sphereShape, new CANNON.Vec3( 4, 0, 2));

          body.position.set(-2,0,6);
          body2.position.set(2,0,6);
          world.add(body);
          demo.addVisual(body);
          world.add(body2);
          demo.addVisual(body2);
        });
````

**Comment by schteppe** [comment]
Hi, 

I believe I've already fixed this bug. Try building the most recent master branch locally and it should work.

Thanks for using Cannon!

Stefan

**Comment by ndeineko** [comment]
Thanks! it works a expected now

**Comment by schteppe** [comment]
Awesome! Let me know if you run into any other bugs.

Stefan
