### ISSUE TITLE
Having trouble implementing a heightmap with the FPS demo

### ISSUE THREAD

**Issue by YiyeUniverse** [schteppe/cannon.js#183]
Hello all! Sorry, I will preface this question with the phrase "N00B Question" so proceed with caution. I have bee experimenting with Cannon.js for a while now and think it is a perfect fit for my project! I'd ideally like to use the heightfield feature to make a terrain for my game. I have tried using the method in the documentation and in the raycasting vehicle demo. Is there a recommended way to show the visuals for the heightmap in three.js using the data provided in:
var matrix = [];
            var sizeX = 64,
                sizeY = 64;

            for (var i = 0; i < sizeX; i++) {
                matrix.push([]);
                for (var j = 0; j < sizeY; j++) {
                    var height = Math.cos(i / sizeX * Math.PI * 5) * Math.cos(j/sizeY * Math.PI * 5) * 2 + 2;
                    if(i===0 || i === sizeX-1 || j===0 || j === sizeY-1)
                        height = 3;
                    matrix[i].push(height);
                }
            }

            var hfShape = new CANNON.Heightfield(matrix, {
                elementSize: 1000 / sizeX
            });
            var hfBody = new CANNON.Body({ mass: 0 });
            hfBody.addShape(hfShape);
           // hfBody.position.set(-sizeX * hfShape.elementSize / 2, -sizeY * hfShape.elementSize / 2, -1);
		   hfBody.position.set(0,0,0);
           world.add(hfBody);

I have used box or sphere collision for everything else and that's quite simple to show but the heightmap has stumped me a bit.
Kind regards,
Matt

**Comment by schteppe** [comment]
Hi,
Maybe have a look at how it is done in the Demo class? https://github.com/schteppe/cannon.js/blob/master/src/demo/Demo.js#L1042

**Comment by YiyeUniverse** [comment]
Hadn't thought of that! Thank you very much!

**Comment by schteppe** [comment]
No problem! Also check out the new debug renderer for three.js: https://github.com/schteppe/cannon.js/tree/master/tools/threejs

**Comment by YiyeUniverse** [comment]
Yeah I saw that on Twitter! Looks really useful! Giving it a download now before my exclamation mark limit runs out!

**Comment by YiyeUniverse** [comment]
Thank you so much! Just a 90* rotation and a texture update away from greatness! You have no idea how happy I am. Thanks again! 

![27thfebruaryterrain](https://cloud.githubusercontent.com/assets/3456711/6423413/9bbba396-bedd-11e4-82a0-bfee7c04a36c.jpg)

**Comment by schteppe** [comment]
Awesome!
