### ISSUE TITLE
SAPBroadphase > insertionSortXYZ useless?

### ISSUE THREAD

**Issue by jgottero** [schteppe/cannon.js#186]
I looked at SAPBroadphase source code, and I've found 3 functions insertionSortX / insertionSortY / insertionSortZ which are used nowhere. Are these functions useful? If not they could be removed to save 0,5kb... wow!! ;-)

NB: I'm writing a GWT wrapper over your fantastic library, that's why I'm reviewing each method ;)

**Comment by schteppe** [comment]
Hmm... They're not used? In .sortList()? Gotta double check on my laptop tomorrow.

Thanks a bunch for your work, it's greatly appreciated!

**Comment by jgottero** [comment]
Damn you are totally right, how did I miss this one... Sorry, my bad!
