### ISSUE TITLE
Problem with CannonJS 0.6.1 and BabylonJS 2.0

### ISSUE THREAD

**Issue by jimk1955** [schteppe/cannon.js#190]
Hello,

I keep getting the following error with the latest version (as of 3/12/2015) of CannonJS:

[Log] BJS - [19:47:42]: Babylon.js engine (v2.0.0) launched (babylon.2.0.js, line 3)
[Error] TypeError: 0.25 is not a valid argument for 'in' (evaluating 'key in options')
	defaults (cannon_0.6.1.js, line 9567)
	ContactMaterial (cannon_0.6.1.js, line 3308)
	_addMaterial (babylon.2.0.js, line 16)
	_createRigidBodyFromShape (babylon.2.0.js, line 16)
	_createBox (babylon.2.0.js, line 16)
	registerMesh (babylon.2.0.js, line 16)
	_registerMesh (babylon.2.0.js, line 13)
	setPhysicsState (babylon.2.0.js, line 8)
	createScene (JIM_test_obj.js, line 74)
	run (JIM_test_obj.js, line 27)
	onload (JIM_test_obj.html, line 26)
	
Here is the line of my code that starts the above error:

createScene (JIM_test_obj.js, line 74):	ground.setPhysicsState(BABYLON.PhysicsEngine.BoxImpostor, {mass:0, restitution:0.5, friction:0.5});

I would appreciate any help.

Thank You.

Jim

**Comment by schteppe** [comment]
Hi,

Is Babylon 2.0 supposed to work with the latest cannon.js? In that case, could you provide a live example?

**Comment by jimk1955** [comment]
Hi,

That is a very good question.
I had assumed so, but perhaps I am mistaken.
Is there a way to tell when they would become compatible?
Sorry for the dumb question.

- Jim

**Comment by schteppe** [comment]
There are no dumb questions :)

I have no idea what the Babylon.js guys plan. Ask them? Until they upgrade you should probably use their supported version. You can find it in the root of their github repo: https://github.com/BabylonJS/Babylon.js/blob/master/cannon.js

**Comment by jimk1955** [comment]
Thank You.

Jim
