### ISSUE TITLE
Add a more prominent link to the docs.

### ISSUE THREAD

**Issue by bnolan** [schteppe/cannon.js#192]
Here...

![screen shot 2015-04-04 at 7 52 31 pm](https://cloud.githubusercontent.com/assets/17499/6991771/2d6ddcae-db04-11e4-9cd1-39008f94b699.png)

**Comment by schteppe** [comment]
Good idea! I should move that site to gh-pages while I'm at it, right now it's hosted somewhere else...

**Comment by bnolan** [comment]
:+1:
