### ISSUE TITLE
Readme example is incorrect

### ISSUE THREAD

**Issue by bnolan** [schteppe/cannon.js#197]
Passing a gravity parameter to cannon.world initializer doesn't work, you need to call world.gravity.set.

:(

```

// Setup our world
var world = new CANNON.World({
   gravity: new CANNON.Vec3(0, 0, -9.82) // m/s²
});
world.gravity.set(0, 0, -20);

```

**Comment by schteppe** [comment]
Fixed the readme and quickly added that feature. Will revert the example on next release. 

Thanks!
