### ISSUE TITLE
Webpack warning: pre-built javascript file

### ISSUE THREAD

**Issue by tbo** [schteppe/cannon.js#199]
I'm using cannon.js in combination with webpack. It works but outputs the following warning:

WARNING in ./~/cannon/build/cannon.js
Critical dependencies:
24:432-439 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/cannon/build/cannon.js 24:432-439

I changed the "main" entry of the packages.json to "./src/Cannon.js" and it works just fine. Is there any reason, why it references "./build/cannon.js" instead of "./src/Cannon.js"?

**Comment by schteppe** [comment]
Don't think there's any reason. Actually, pointing to src/Cannon.js would be better, for example when debugging in Node.js.

Wanna submit a PR?

**Comment by tbo** [comment]
@schteppe PR:  #200
