### ISSUE TITLE
Bodies which are constrained to non-colliding bodies cannot be woken by forces from those non-colliding bodies

### ISSUE THREAD

**Issue by josephrocca** [schteppe/cannon.js#214]
I'm in a rush at the moment, but can explain further if asked - just noting this here so I don't forget. This isn't an urgent problem - it has an easy work-around in most (though definitely not all) cases.

Basically I've got this set up:
```
[body1] --- [body2] --- [body3]
```
The `---` represents a hinge joint. `body2` is constrained via hinge joints to `body1` and `body3` on either side. I have set up collision filtering so `body2` cannot collide with `body1` or `body3`. I have allowed all bodies to sleep.

If the 3 masses stay still for long enough then they all sleep, but when I turn on the hinge motors `body1` and `body3` spin around `body2` and (here's the interesting part) `body2` remains **permanently fixed** to the world coords that it went to sleep at. Even if `body1` and `body3` are flailing about, hitting into things and imparting a huge force onto `body2` via the hinge constraints, `body2` doesn't budge one bit.

I should note that in my testing both hinge constraints are fixed to the exact centre of `body2` (I'm using it as a '2D hinge joint' - basically I needed a motorised 2 degree-of-freedom joint). I haven't tested any other setup and haven't isolated the problem into a standalone example - sorry, I don't have time at the moment.

The workaround in my case is to simply disable sleeping on `body2` - no big deal since it'll almost always be in motion anyway.

I'm not sure how the implementation of sleeping workings in physics engines and so apologies if this is expected behaviour - but it is counter-intuitive behaviour nontheless, so at least documumenting it may help others who've came across the same problem.

**Comment by schteppe** [comment]
Are you sure that all bodies fall asleep? When you "turn on the hinge motors", do you just run ```hinge.enableMotor()``` or something more?

The expected behavior is that bodies wake up on collision and when constraints are added to them. Anything else is left out to the user: just run ```.wakeUp()``` on the Body you want to wake up :)

**Comment by josephrocca** [comment]
Actually I think you're right - only `body2` falls asleep in my above example. I was calling both of these:
```
hinge.enableMotor();
hinge.setMotorSpeed(speed);
```
It seems like when I let them all fall asleep, the above two statements do nothing - it is only when I `wakeUp()` the bodies that all the motors begin to take effect. This is expected though, as you explained, so we're all good!
