### ISSUE TITLE
Scale the world

### ISSUE THREAD

**Issue by rkrasky** [schteppe/cannon.js#219]
Hi again,

is it possible to scale the world like in the original bullet system?
http://www.bulletphysics.org/mediawiki-1.5.8/index.php?title=Scaling_The_World

**Comment by schteppe** [comment]
Yeah I guess... How could the cannon.js API help you with that?

**Comment by rkrasky** [comment]
A simple getter and setter to scale the world with a number like in bullet would be great!

**Comment by schteppe** [comment]
Can you please point me to the Bullet API docs for this? I started searched in http://bulletphysics.org/Bullet/BulletFull/classbtCollisionWorld.html for "scale", but didn't find anything.

**Comment by rkrasky** [comment]
I'm still searching... :) I get the scaling (not scale) value from AS3 Citrus Engine or Away3DPhysics. Here is the code for the Citrus Engine: 
https://github.com/DaVikingCode/Citrus-Engine/blob/master/srclib/awayphysics/dynamics/AWPDynamicsWorld.as

**Comment by schteppe** [comment]
I see. Well, seems like the Citrus Engine is a game engine, a layer on top of Bullet. When it creates Bullet shapes or applies force, it uses the scaling to scale the values before passing it into Bullet.

In other words, the scaling is not a part of the Bullet API.

**Comment by rkrasky** [comment]
Could you implement it like in Citrus Engine or AwayPhysics?

**Comment by schteppe** [comment]
Anything can be implemented :)
I'm not sure it would be a good idea though. Most game engines implement physics scaling in their own way, and that is necessary to get full control over the physics. I guess that's one of the reasons why Bullet didn't implement it.

**Comment by schteppe** [comment]
@rkrasky If you have any example of a physics engine (not a game engine), that implements world scale, then please enlighten me! I found the source for AwayPhysics and I could not find what I'm looking for. https://github.com/away3d/awayphysics-core-fp11/search?l=as3&q=scale&utf8=%E2%9C%93

**Comment by rkrasky** [comment]
Thanks a lot for still trying to implement it. In AwayPhysics the scaling can be found here:
https://github.com/away3d/awayphysics-core-fp11/blob/master/AwayPhysics/src/awayphysics/dynamics/AWPDynamicsWorld.as
Line 306 is a getter and setter.

**Comment by schteppe** [comment]
It's still under consideration.. I'm curious since I didn't see this built-in scaling before.

Still not fully convinced though. It's really easy to scale stuff in whatever layer the developer has on top of Cannon.js, game engine or not. Is this really worth the effort and bytes?

**Comment by schteppe** [comment]
Considering it not worth it.
