### ISSUE TITLE
Feasibility of Body pooling?

### ISSUE THREAD

**Issue by josephrocca** [schteppe/cannon.js#226]
Hey Schteppe,

I'm thinking about eventually pooling bodies in my simulation, but it doesn't look like there's a way to 'disable' bodies in cannon? The `KINEMATIC` body type is almost there, but since the body still responds to collision events, I'd potentially lose a ffair bit of performance if my pool gets big.

I'm guessing that it would be a waste of time having one huge object pool with all sorts of shapes in it, so I'd be aiming to pool object by geometry - i.e. I'd have a pool for boxes, a pool for spheres, etc. Would that make sense? And in that case, is it possible to change the dimensions of a box/sphere/etc.?

So I suppose the two reqirements for pooling are:
1. must be able to disable objects (so they don't interact with anything and essentially don't exist)
2. must be able to change dimensions of disabled objects, and then re-enable them

Are these to things possible at the moment? Is pooling a silly idea?

Thanks!

**Comment by schteppe** [comment]
1. Remove the body from the world?
2. More complicated... The easiest solution here would be to create a new instance of the shape. Alternatively, make sure the full shape state is like it is at creation. Check what is done in each shape constructor. I plan to add an .update() method for all shapes that does this, but haven't gotten there yet. Once you have the shapes updated, you must update the mass properties and bounding volumes of the Body (just remove and add the shapes to the Body).

Should make a pool demo when the .update() method is in, I think this is a common problem :)

**Comment by josephrocca** [comment]
Okay, cool, sounds achievable. I'll have a look at this when I get around to optimisation. Thanks :)
