### ISSUE TITLE
compound body center of mass

### ISSUE THREAD

**Issue by WillWhiteneck** [schteppe/cannon.js#230]
Thanks for the awesome physics library -- it's fast and works nicely with three.js! :smile: Letely I've been playing around with compound bodies using .addShape(...); like this [example](https://github.com/schteppe/cannon.js/blob/master/demos/compound.html). It all works as expected except that, as I add shapes, the body behaves as though the center of mass is in the wrong place. It seems like it's located at the body's origin. My intention is to have the COM move as I add shapes to the body -- I'm assuming the shapes all have the same density. Is there something else I need to do?

**Comment by schteppe** [comment]
Hi,
The Body mass won't move as you add shapes - this has to be done manually.
What you have to do is computing a new COM and move the Body there, and then move all shapes the reverse distance. I made a method for this in p2.js, maybe it's easy enough to port to cannon? https://github.com/schteppe/p2.js/blob/master/src/objects/Body.js#L862

**Comment by WillWhiteneck** [comment]
Thank you! I got it to work. My program uses voxel shapes, so it was easy enough to calculate the COM and move everything like you said.

	var updateCOM = function( body ) {
		//first calculate the center of mass
		var com = new CANNON.Vec3();
		body.shapeOffsets.forEach( function( offset ) {
			com.vadd( offset, com );
		});
		com.scale( 1/body.shapes.length, com );

		//move the shapes so the body origin is at the COM
		body.shapeOffsets.forEach( function( offset ) {
			offset.vsub( com, offset );
		});

		//now move the body so the shapes' net displacement is 0
		body.position.vadd( com, body.position );
	};
