### ISSUE TITLE
Body's Center of Mass

### ISSUE THREAD

**Issue by ilanusse** [schteppe/cannon.js#232]
Hello!

I believe my rigid body's center of mass is slightly out of place and I can't seem to set it manually through the Body class.

What can I do to set it manually?

Thanks!

**Comment by WillWhiteneck** [comment]
Hi. You're in good company, I asked this question a few days ago https://github.com/schteppe/cannon.js/issues/230. First you need to calculate the position of the COM. Next change the shape's offset inside the body so the COM is at the origin. Finally move the body the opposite direction to the net displacement is 0.

    var updateCOM = function( body ) {

    //first calculate the center of mass
    var com = new CANNON.Vec3();
    body.shapeOffsets.forEach( function( offset ) {
        com.vadd( offset, com );
    });

    com.scale( 1/body.shapes.length, com );
    //move the shapes so the body origin is at the COM
    body.shapeOffsets.forEach( function( offset ) {
        offset.vsub( com, offset );
    });

    //now move the body so the shapes' net displacement is 0
    var worldCOM = new CANNON.Vec3();
    body.vectorToWorldFrame( com, worldCOM );
    body.position.vadd( worldCOM, body.position );
    };

**Comment by ilanusse** [comment]
Thanks a lot!
