### ISSUE TITLE
How does Body.angularVelocity work?

### ISSUE THREAD

**Issue by ilanusse** [schteppe/cannon.js#234]
Are the x, y, z axes in the Vec3 the world axes or the object's axes?

Should it be in rads/s or degrees/s?

**Comment by josephrocca** [comment]
All angles are in radians as far as I am aware. +1 to the question about local/global axes. It would be good if the documentation specified this for `.force`, `.torque`, and any other properties of a `Body` where there might be some confusion.

**Comment by schteppe** [comment]
Fixed ! Sorry for the delay.

**Comment by ilanusse** [comment]
Thanks a lot! :+1:
