### ISSUE TITLE
Calculating the force that a motor is currently applying?

### ISSUE THREAD

**Issue by josephrocca** [schteppe/cannon.js#235]
I'm trying to get an approximation for the work done by a motor during a single frame.

My guess is that since I know the motor's target speed, and it's maximum force, all I need is the actual speed of the motor and I can make some approximation based on how cannon applies force given the difference between the current and target angular velocities?

So before I go about trying to calculate the actual motor speeds, I though I'd check to see that my reasoning is correct. Is there a better way to do this?

Thanks!

**Comment by schteppe** [comment]
Well, the applied force depends on a lot of things. What if the engine drives a huuuuge wheel and tries to slow it down? The applied force will be at max, but the angular velocity is still high.

As with the other constraint equations, you can get the .multiplier from the Hinge:

```js
hingeConstraint.motorEquation.multiplier
```

This value should be proportional to the current applied force. Try it?

**Comment by josephrocca** [comment]
Ahh, okay, so the `multiplier` of the `motorEquation` is specifically related to the force which the motor is applying? And then the other two equation types (`rotationalEquation` and `contactEquation`) have `multiplier`s which make up for the other forces that the constraint is under?

**Comment by schteppe** [comment]
Yes! It should be proportional to the force that the equation adds to the bodies. You'll have to use the bleeding edge version though, added it quite recently.

**Comment by josephrocca** [comment]
Great! This will make things much easier. Thanks :)
