### ISSUE TITLE
Technical specifications of Cannon's engine?

### ISSUE THREAD

**Issue by josephrocca** [schteppe/cannon.js#238]
Hey Schteppe,

I'm writing a report and doing a presentation about my project so far (the one I've been asking all these questions for), and I figured it'd be good to know at least a tiny bit about cannon's back-end.

If you could just give me keywords, or direct me to wikipedia articles, that'd be great. I've read very briefly about penalty/constraint/impulse based methods.

Cheers :)

**Comment by schteppe** [comment]
All right!

Cannon was originally made as a lab at this course at Umeå University: http://www8.cs.umu.se/kurser/5DV058/VT15/index.html

Cannon is a rigid body physics engine. It uses the SPOOK stepper, and its equation is derived from verlet. Constraints are formulated using Jacobians, and to solve them, a built in Gauss-Seidel solver is used. Friction is based on a scaled box model.

A key document is this one: http://www8.cs.umu.se/kurser/5DV058/VT15/lectures/SPOOKlabnotes.pdf

Regarding the SPOOK stepper stuff, please refer to "Ghosts and Machines" by Claude Lacoursière. See the bibliography section in the pdf above.

Let me know if you need something more. And good luck with the report!

**Comment by josephrocca** [comment]
Great - this is perfect, I'll get reading!

Thanks!
