### ISSUE TITLE
Is it possible to make a water?

### ISSUE THREAD

**Issue by sasha240100** [schteppe/cannon.js#242]
I am looking for a way how to make water on my heightfield

**Comment by schteppe** [comment]
There's nothing built into cannon.js to simulate water.. Except the experimental SPH support. What kind of effect are you looking for? Maybe something like this is enough? http://schteppe.github.io/p2.js/demos/buoyancy.html

**Comment by sasha240100** [comment]
But how to implement it in 3D?

**Comment by schteppe** [comment]
This is the SPH one: http://schteppe.github.io/cannon.js/demos/sph.html

Should be fairly easy to port it to 3D.. just do volumes instead of areas, etc.. p2 is similar to cannon so it should be straight forward I think

**Comment by sasha240100** [comment]
@schteppe Thank you! :)

**Comment by SteveOW** [comment]
It would be nice to have particles-to-heightfield implemented so we can simulate flowing water.

**Comment by duhaime** [comment]
@sasha240100 @schteppe I think this issue can be closed
