### ISSUE TITLE
Prerender Physics!

### ISSUE THREAD

**Issue by ilanusse** [schteppe/cannon.js#243]
Hello! I was trying to bring up my FPS by doing the physics calculations with `CANNON` BEFORE doing the rendering.

Somehow, when I do the calc **before** rendering (saving the body's positions and quaternions frame-per-frame in an object), the model I'm using still goes through the floor as if collisions weren't activated. It only goes partly through since the object is using the last body position as a final position. The rendered scene does NOT have a `CANNON.World` instantiated, it is merely a `Three.js` scene.

However, in another scene I do the exact same thing and the collision works fine. Here comes the problem: I compared the positions and quaternions frame by frame and they are **exactly** the same.

Do you have any idea why this might be? Can a body's position and quaternion field sometimes not accurately display where it actually is?

**Comment by schteppe** [comment]
Hi,
Cool approach to the problem !

It sounds like something fishy is going on in your code. Can you tell me how you store and restore the positions and quaternions?

**Comment by ilanusse** [comment]
@schteppe Hello! I'm sorry for bothering you with this, I was saving the positions incorrectly, so nevermind!

On a semirelated note, is there any way I can change a body's center of mass without an offset? I want to change the CoM but if I apply an offset to the body it makes the object pass through other objects in some parts of the mesh.

**Comment by ilanusse** [comment]
Oh, and thanks by the way :)

**Comment by schteppe** [comment]
No problemo :)

To move the CM you put an offset on each shape when you add them. Say you want the CM more to the right.. Then move all shapes to the left. There are currently no other ways of doing this.
