### ISSUE TITLE
heightfield elementSize is not for all axes

### ISSUE THREAD

**Issue by rbozan** [schteppe/cannon.js#245]
It currently acts only for the X and Y axis, but I suggest to use it for all the axis as not every use case has the gravity to the Z axis. I currently use the Y axis for height, X / Z for forward/backward, left/right, and because elementSize does not apply to all axes it's pretty useless for me.

**Comment by schteppe** [comment]
You can always rotate the container body (or the shape itself) to make the shape face in whatever direction you want. This way, the same implementation can be used no matter if your "up" axis is X, Y, Z, -X or any other vector.

**Comment by rbozan** [comment]
Thanks for the idea.
