### ISSUE TITLE
Hooking into collision/constraints

### ISSUE THREAD

**Issue by andyhall** [schteppe/cannon.js#247]
Hi,

Possibly odd question. Is it possible to hook into Cannon's collision or constraint handling, so as to simulate obstructions that depend on data that Cannon doesn't know about?

The use case is for a nontrivial voxel scene, where it's not feasible to create a rigid body for every voxel. If there was a way to, say, hook into wherever Cannon resolves collisions, I could inspect each body's position and velocity and create the extra collisions I need. 

Or alternately, if there's some event I could catch *after* bodies have been given new velocities but *before* collisions are resolved, then I imagine I could keep a pool of static cube or plane objects, and move them to the needed positions.

Is such a thing is possible with Cannon, or could it be done if I hacked in a new event that fires partway through the step function?

**Comment by schteppe** [comment]
Hi,

I think the easiest way to do this is to create a new Shape class that can compute its AABB, look up voxel data etc. And then write a collision handler function or two for the Narrowphase. I'm not 100% sure but it should be possible to patch these things onto the built Cannon lib.

This commit shows everything I needed to do to implement Trimesh and its collision against plane, it might be useful: https://github.com/schteppe/cannon.js/commit/b45172f1729431a08dabb4fe71b39054b5bc0094

**Comment by andyhall** [comment]
Ahh, that makes sense. Now that I look closely, it would need to closely mirror the implementation of `Heightfield`, right? And basically the only code needed would be a shape class to report infinite broadphase sizes, and the relevant nearphase test functions?

**Comment by schteppe** [comment]
Yes, you got it!

**Comment by andyhall** [comment]
That sounds a lot more doable than I'd thought. Thanks!
