### ISSUE TITLE
How do I find which way my box is facing after rolling it?

### ISSUE THREAD

**Issue by dethstrobe** [schteppe/cannon.js#248]
Hello, I'm making a dice roller. I was able to rotate the dice (a box) in some random direction by applying angularVelocity and/or setting the quaternion to a random quaternion.

My understanding of quaternions is amateur at best. As my assumption was that it's a vector with w being the rotation in the vector's direction. But as I've done tests after rolling the dice the quaternion positions don't line up to how I think it should.

Is there a way to determine which direction the box is facing or which side of the box is facing up on the Z-axis after rolling it?

If he helps, [here is a fiddle] (http://jsfiddle.net/dethstrobe/o7ms50to/5/) with some of the code I'm trying to work with.

**Comment by schteppe** [comment]
Hi! As long as you normalize the quaternion you should be fine. Consider using quaternion.fromAxisAngle(). A quaternion is as you say, an axis and a rotation around that axis.

To check if a box face is pointing up, you can compute the dot product with the face normal and the up vector (both vectors in world space). If the dot product is large enough, the face is facing up. 

```js
var localFaceDir = new Vec3(1,0,0);
var worldFaceDir = new Vec3();
body.quaternion.vmult(localFaceDir, worldFaceDir);
var faceIsPointingUp = worldFaceDir.dot(upVector) > 0.5;
```

(Untested code)

If you do this for all faces you know which one is up. 

An optimization is to transform the up vector into the local "dice space" instead. Try it if you like :)

**Comment by dethstrobe** [comment]
Thanks for your suggestion. It was enough of a clue for me to figure it out. [Here is a fiddle](http://jsfiddle.net/dethstrobe/o7ms50to/8/) with it in action.

			var side = {
				one: new CANNON.Vec3(),
				two: new CANNON.Vec3(),
				three: new CANNON.Vec3(),
				four: new CANNON.Vec3(),
				five: new CANNON.Vec3(),
				six: new CANNON.Vec3()
			};

			cubeBody.vectorToWorldFrame(new CANNON.Vec3(0, 0, 1), side.one);
			cubeBody.vectorToWorldFrame(new CANNON.Vec3(0, 1, 0), side.two);
			cubeBody.vectorToWorldFrame(new CANNON.Vec3(-1, 0, 0), side.three);
			cubeBody.vectorToWorldFrame(new CANNON.Vec3(1, 0, 0), side.four);
			cubeBody.vectorToWorldFrame(new CANNON.Vec3(0, -1, 0), side.five);
			cubeBody.vectorToWorldFrame(new CANNON.Vec3(0, 0, -1), side.six);

			var upVector = new CANNON.Vec3(0, 0, 1);

			switch (true) {
				case side.one.dot(upVector) > .9:
					console.log("landed on side 1");
					break;
				case side.two.dot(upVector) > .9:
					console.log("landed on side 2");
					break;
				case side.three.dot(upVector) > .9:
					console.log("landed on side 3");
					break;
				case side.four.dot(upVector) > .9:
					console.log("landed on side 4");
					break;
				case side.five.dot(upVector) > .9:
					console.log("landed on side 5");
					break;
				case side.six.dot(upVector) > .9:
					console.log("landed on side 6");
					break;
				default:
					console.error("Error! dice side not found");
			}

I'll see if I can't refactor it later, but its logging the correct side every time the cube stops. So thanks again for the help.

**Comment by schteppe** [comment]
Cool! I'm glad to be able to help :)
