### ISSUE TITLE
Removing constraints?

### ISSUE THREAD

**Issue by YiyeUniverse** [schteppe/cannon.js#250]
Is there a way to remove or break a constraint? I am currently making a game where the player can shoot a ball which will stick, and then the player will be able to swing off it like a grappling hook. I am using a constraint to allow the player to swing from this point, but would like to break it when the mouse is released. Is there a way to easily remove a constraint? All I can find are disable() and enable(), but the grappling point is being deleted so I would ideally like both to be removed at the same time. 

Kind regards,
Matthew

**Comment by schteppe** [comment]
Hi. Did you try world.removeConstraint()? http://schteppe.github.io/cannon.js/docs/classes/World.html#method_removeConstraint

Also see the tear demo: https://github.com/schteppe/cannon.js/blob/master/demos/tear.html

**Comment by YiyeUniverse** [comment]
Thank you very much for the quick reply! It worked! I will send you a link to the game when I'm done with this bit! I just think grappling hooks are always fun in games!
