### ISSUE TITLE
Collider completly within zone

### ISSUE THREAD

**Issue by harraps** [schteppe/cannon.js#251]
Hello is there a way to check if a collider is completly within a zone.
Like I have a cylinder and I want to check if it is inside a rectangle.

**Comment by schteppe** [comment]
Currently no. Do other physics engines offer this?

Perhaps you could solve it in some other way, like making a box "surface" out of 6 boxes and check when the cylinder gets inside and stops overlapping them... Does this make sense?

**Comment by harraps** [comment]
Well if that's how it is, i would rather use raycasts then.
My shape is a cylinder which height's is 4 times bigger than its radius. So I just need to put raycasts around the rectangular shape and some other raycasts inside.
If the collider is touched by the outer rays, it's not inside the zone.
If it collide with the inner rays only, than it's within the zone.

**Comment by schteppe** [comment]
Sounds legit!
