### ISSUE TITLE
Proper way to destroy a cannonjs world?

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#252]
I have an app where I switch between editor and game engine repeatedly - and i'm trying to debug performance issues. I'm creating a new cannonjs world every time the game loads. What's the proper way to destroy the world on game end? I don't see a destroy or dispose method on http://schteppe.github.io/cannon.js/docs/classes/World.html

**Comment by schteppe** [comment]
Hi, the World does not have a destroy method yet. It's not been needed. The cannon stuff allocated are just regular JS objects. If you remove all references to them, the world will be garbage collected.

If you want to reuse the World instance, you can remove all things you added to it, like bodies, constraints etc. In p2.js there's a clear method that does all this. Maybe this is what you're looking for? https://github.com/schteppe/p2.js/blob/master/src/world/World.js#L1075

**Comment by DelvarWorld** [comment]
Works for me!
