### ISSUE TITLE
Why don't any of the examples use applyForce / applyImpulse?

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#257]
I'm trying to debug my jumping code (as mentioned on Twitter) and when looking at the FPS example code, http://schteppe.github.io/cannon.js/examples/js/PointerLockControls.js, to make the player jump, the velocity property of the body is mutated directly:

    var velocity = cannonBody.velocity;

    ...

            case 32: // space
                if ( canJump === true ){
                    velocity.y = jumpVelocity;

Why do you do this instead of using `applyForce` or `applyImpulse`? Are those innappropriate to use for applying movement forces to a player?

**Comment by schteppe** [comment]
If you run applyForce or applyImpulse, it will *add* to ```body.force``` or ```body.velocity```. That makes the jump height unpredictable, which isn't acceptable when making a game. Instead, if you set the absolute value of the velocity, you always know what height you get.

**Comment by DelvarWorld** [comment]
ah ok, thanks!

**Comment by DelvarWorld** [comment]
On these lines of the FPS demo, `PointerLockControls.js`

        // Add to the object
        velocity.x += inputVelocity.x;
        velocity.z += inputVelocity.z;

Isn't that the same as `applyImpulse`?

**Comment by schteppe** [comment]
Yeah, it is! But applyImpulse can add angular velocity too, depending on where you apply the impulse.
