### ISSUE TITLE
Giving a collisionFilterGroup without a collisionFilterMask prevents all collision

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#261]
If you simply give an object a `collisionFilterGroup`, but don't give it a `collisionFilterMask`, then it won't collide with anything. I'm not sure why this would ever be a desired behavior? In my case, I have a bunch of objects, but I only want `C` to collide with `A`, and everything else to work fine. So I give `C.collisionFilterMask` `A`'s group, but then `A` doesn't collide with anything and falls right through my level.

**Comment by schteppe** [comment]
Yeah. So what do you suggest instead? Default both values to -1?

**Comment by DelvarWorld** [comment]
i'm not familiar with the internal mechanics of how it works, and i'm happy to dig in if I have some free time and submit a PR. The behavior I would expect basically is nothing different to happen if a group is specified but not a mask. I would expect the object to interact with all other objects normally.

**Comment by schteppe** [comment]
You are right. 

This tutorial is pretty good! http://www.iforce2d.net/b2dtut/collision-filtering

It also suggests that the default mask is "collide with everything" in box2d. Cannon should probably do the same :)

**Comment by schteppe** [comment]
@DelvarWorld Better?

**Comment by DelvarWorld** [comment]
Looks good to me!
