### ISSUE TITLE
Constrain a body entirely to 1 or 2 dimensions?

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#262]
Similar to [this issue](https://github.com/schteppe/cannon.js/issues/151) but I don't know if the mechanics are the same - I'm making a 2.5d game and need to constrain all of my bodies to only move on the x and z axes (y will always be a fixed value). As I commented in the other thread, setting linearFactor and angularFactor to 0 for the Y axis kind of works, but my objects can still leave the Y plane if forces are applied to them. As in I can push them out of alignment with Y 0 with my character in the game.

Is there an internal mechanism cannon has for axis constraints? or do you have a suggested method for doing so?

**Comment by schteppe** [comment]
The idea is that linearFactor and angularFactor should do what you need. How can I reproduce this? Just apply force to a body?

Which version of Cannon are you using?

**Comment by DelvarWorld** [comment]
Oh, it seems like I wasn't constraining angular velocity correctly, and a few other unrelated factors. Setting the `y` component factor for linear and angular on all my objects seems to work!

**Comment by nathanosdev** [comment]
There is literally not a single mention of linearFactor or angularFactor in the source code anywhere,
I've been searching and searching on how to achieve such a trivial task and getting absolutely nowhere.
I've literally never found any library so difficult to learn how to use.

**Comment by AndrewRayCode** [comment]
[What?](https://github.com/schteppe/cannon.js/search?utf8=%E2%9C%93&q=linearFactor)

**Comment by nathanosdev** [comment]
Sorry! But they are not in either the NPM or Bower packages....
It seems the tag 0.6.2 was released 2 years ago and this is what gets downloaded by NPM or Bower, which would explain why I'm having such a nightmare with this, I'm on ridiculously old code.

Thanks for indirectly highlighting that out for me!
