### ISSUE TITLE
Checking for persistent contacts

### ISSUE THREAD

**Issue by iandanforth** [schteppe/cannon.js#264]
During every timestep I want to know which objects are in contact. It appears that world.contacts provides this, but once the world has settled, that array is cleaned up. allowSleep = false, keeps the array populated obviously, but that's a pretty big hammer. 

Is there an intermediate way to, at any step, find all contact points?

**Comment by schteppe** [comment]
Yes, you can always get the contacts between any step?

Sleeping bodies won't generate contacts, to improve performance. Do you need to check the contacts even though they are asleep?

Maybe you could use the ```sleep```, ```beginContact``` and ```endContact``` events?

**Comment by iandanforth** [comment]
Ahh so if there are two sleeping bodies in contact if they stop being in contact (due to being moved away from one another) the endContact will fire?

My use case is an odd one. I'd like to simulate touch sensors, which while touching, are continually active, and when touch ends go inactive.

It sounds like with the endContact event I can capture the sleeping-in-contact -> awake-not-in-contact transition. Is that correct?

Thanks for the reply!

**Comment by schteppe** [comment]
When a body falls asleep, it will stop moving and not generate any contacts. If it has contacts while it falls asleep, I think endContact will be emitted (need to verify this). When it wakes up, it will start generating contacts again and beginContact should be fired.

I don't really understand your setup. Could you explain it further? How do these sensors move? Why do they need to sleep at all (an alternative is to remove them from the world).

**Comment by iandanforth** [comment]
I ended up adding particles to the face of a geometry to start exploring what I'm getting at here. Closing this in favor of a new, more specific question.
