### ISSUE TITLE
Issue with forces and friction

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#273]
I'm designing a game that has blocks you can push, and things that cause forces, like air puffers.

I've made a simple "machine" in my game where a block is pushed right by an air puffer, then it falls, then it's pushed left by another puffer. I would expect this to work smoothly. However, as you can see in the (10mb) gifv movie below, there is some unexpected behavior.

http://i.imgur.com/HdHiA1Z.gifv

There's a few issues I see here:

1. The pushy block moves much faster on the top platform than on the bottom, where it's crawling. I have verified that both air puffers are applying the same magnitude of force to the pushy block. And yet the bottom puffer makes the block move more slowly. The contact materials are the same in both cases (code below).
2. You can see the block "sticks" to the left wall for a while until it (for an unknown reason) decides to fall down. (Ignore the player jumping - that was just my boredom). Ideally I'd like gravity to be the overwhelming force here and have it fall down as soon as it's over the opening.

I'm having trouble figuring out what's going on here. The pushy block has its own material and *all* walls share a wall material. The contact equation is defined as such:

```js
const puhshyToWallContact = new CANNON.ContactMaterial( pushyMaterial, wallMaterial, {
    friction: 0.2,
    // Bounciness (0-1, higher is bouncier). How much energy is conserved
    // after a collision
    restitution: 0,
    contactEquationStiffness: 1e12,
    contactEquationRelaxation: 3,
    frictionEquationStiffness: 1e8,
    frictionEquationRegularizationTime: 3,
    contactEquationRegularizationTime: 3,
});
```
(I'm assuming that I don't also need to define a `ContactMaterial` for the reverse `wallMaterial, pushyMaterial`?)

I will add here that if I set friction to 0 in the above code snippet I get much smoother sliding, but then I get issues with the player being able to push blocks that are too heavy and shouldn't be pushable by the player.

I constrain all bodies to 2.5d movement with no rotation:
```js
angularFactor: new CANNON.Vec3( 0, 0, 0 ),
linearFactor:new CANNON.Vec3( 1, 0, 1 );
```

To apply the force of a puffer to the pushy block, i'm doing the fairly simple:
```js
body.velocity.x += impulseVector.x;
body.velocity.z += impulseVector.z;
```

Do you have any suggestion for debugging this?

**Comment by schteppe** [comment]
The first thing that comes to my mind is, why not use a 2D physics engine for this seemingly 2d game? It would probably resolve this bug - 3D contacts can potentially adds more contacts that can make the boxes jam, or get more friction than they should.

Second thing is the way you apply "force" - not sure if you really should do it this way. How about applying force instead? You're disrupting the friction solving by modifying the velocity.

Are vertical wall blocks merged into one? If not, this may be the reason why the box gets stuck. You see, even if you have two cube blocks on top of each other to form a wall, there's a risk that your falling block will penetrate the top block and rest on top of the bottom block. If you render all the contact points (see https://github.com/schteppe/cannon.js/blob/master/src/demo/Demo.js#L282), you can debug what happens.

There's also a risk that it looks up the wrong contact material from your material pair... It should not, but you can double check this. Put a breakpoint around here: https://github.com/schteppe/cannon.js/blob/master/src/world/World.js#L707

Let me know how it goes!

**Comment by schteppe** [comment]
By the way, here's a good tutorial if you want to learn why merging wall blocks is a good idea: http://www.iforce2d.net/b2dtut/ghost-vertices

**Comment by DelvarWorld** [comment]
Nothing conclusive yet, but here's what I've tried so far:

I changed the puffer force to use `applyImpulse`:
```js
body.applyImpulse( impulseVector, relativeCannonPoint );
```
I tried `applyForce` (with the same parameters) but it wouldn't move the object, and I haven't taken the time to debug why yet.

I made sure the walls the block is sliding along are solid, including the back wall, and colored the solid blocks to show as much:

![screen shot 2016-03-18 at 12 15 34 pm](https://cloud.githubusercontent.com/assets/79215/13889396/97e222c2-ed03-11e5-8089-2303ecfe6b4d.png)

I turned on the contact points in my debug mode. I styled them as green oblong spheres. You can see there's only 2 (or maybe 4 overlapping) contact points for the sliding cube (only the green stretched spheres are contact points, the rest are for other debugging):

![screen shot 2016-03-18 at 12 12 45 pm](https://cloud.githubusercontent.com/assets/79215/13889449/dd6345d8-ed03-11e5-9dc0-70be552671aa.png)

And I verified there's only 2 (or maybe 4) contact points when it's pushed against the back wall:

![screen shot 2016-03-18 at 12 12 51 pm](https://cloud.githubusercontent.com/assets/79215/13889458/e53a0990-ed03-11e5-9dcd-3c8120192bdd.png)

The behavior is still the same with these changes. Debugging the contact materials next...

**Comment by DelvarWorld** [comment]
Also, when my boxes fall with any kind of left or right velocity, they tend to bounce between the walls. You can see this at the end of the gif in the original clip, the box falls through the 1 unit wide gap (the box is about 0.8 units across) and it bounces back and forth between walls, slowing it down. Is there a way to minimize that bounciness?

**Comment by DelvarWorld** [comment]
Now using p2: https://twitter.com/andrewray/status/712371665485705216

Good enough for me :)
