### ISSUE TITLE
How to make Boundig Boxes visible

### ISSUE THREAD

**Issue by tomo0613** [schteppe/cannon.js#281]
I imported a Blender object (~.dae) to my ThreeJS scene and I'd like to create a physical body to it with CannonJS, I could do that, with making a compound shape from Boxes, but can only guess about, what size and where the Boxes should be.
It would be a lot easier if i could make the AABBs visible.
I found a pretty demo:  http://matthiasschuetz.com/three-basicthirdpersongame/docs.php
it says " You should always check if the bounding box was created correctly. This can be done by calling _cannon.showAABBs().init(); in initComponents ... " ,so it looks like possible, but for me it's not working. (probably an outdated CannonJS version)
Is it possible to do that, with the current version?

And if u have 5 more mins:
http://stackoverflow.com/questions/36695768/moving-cannonjs-object-in-3d-according-to-its-quaternion

**Comment by sasha240100** [comment]
@tomo0613, for debugging try this: https://github.com/schteppe/cannon.js/blob/master/tools/threejs/CannonDebugRenderer.js

**Comment by tomo0613** [comment]
Works Great, Thanks a lot!

**Comment by sasha240100** [comment]
@tomo0613 :)
