### ISSUE TITLE
SAPBroadphase and null boundingRadius

### ISSUE THREAD

**Issue by yrns** [schteppe/cannon.js#282]
I have a body with no shapes in my world, so `boundingRadius` is never set on the body. In SAPBroadphase, the insertions are done with the bodys' AABBs (which is a point for a body with no shapes), but the `checkBounds` function uses `boundingRadius` for the extents (which is NaN for this body). This causes bodies later in the sorted list to fail the broadphase check regardless of the extents.

The bounding radius isn't set in the constructor (or documented either). Maybe it should default to zero or checkBounds should check for null. I can submit a PR if you're interested.

**Comment by schteppe** [comment]
Added it. Thanks for the heads up!

**Comment by yrns** [comment]
Perfect, thanks!
