### ISSUE TITLE
Meshes disappearing when i update their positions

### ISSUE THREAD

**Issue by tomo0613** [schteppe/cannon.js#284]
I'm trying to make my spaceship fire projectiles.
It looks working fine according to the debug renderer.
[(https://cdn.rawgit.com/tomo0613/test-project-repo/master/index.html)]
[https://codepen.io/Tomo0613/pen/xVjqqK]

`for (var i = 0; i < projectileBodies.length; i+=1) {
    projectileMeshes[i].position.copy(projectileBodies[i].position);
    projectileMeshes[i].quaternion.copy(projectileBodies[i].position);
}`
When i comment out the above section the meshes are showing at the right place, but if I'm try to update the positions, the meshes are disappear, and i have no idea why.
Anybody can help me with this?

(+1) I'm curious what will happen with projectiles when they far enough to not be able to detect them?
Should I write the code to remove them after a certain distance, for better performance?

**Comment by schteppe** [comment]
Looks like you try to copy a position to a quaternion?

This should work better (assuming you're using latest Three.js version and enabled quaternions):

```
projectileMeshes[i].position.copy(projectileBodies[i].position);
projectileMeshes[i].quaternion.copy(projectileBodies[i].quaternion);
```

Yes, removing bodies is good for performance, so if you can, remove as much bodies as you can when you don't need them.

**Comment by tomo0613** [comment]
Aaah :) Thank you so much!
I watched the code for hours, even that two exact lines, and i was unable to notice that.

**Comment by schteppe** [comment]
I'm glad to help :)
