### ISSUE TITLE
Different collision behaviour y-up / z-up

### ISSUE THREAD

**Issue by AtiX** [schteppe/cannon.js#289]
Semi-related issue #12 
CC @timediv

Hi,

I noticed a difference in simulation behavior which I can't explain when using different coordinate systems. My assumption would be that cannon.js should/does not care about whether the rendering uses an y-up approach or an z-up approach and thus what gravity direction is being used (right?).

However, I noticed the following differences. The scene is a box falling down on an endless plane:
1. Y-up (`gravity= 0, -300, 0`, ground plane rotated 90° around x-axis to face y-up) ends up with the following correct result - the box lies flat on the ground: 
   ![flatonground](https://cloud.githubusercontent.com/assets/236678/16015803/ba6be0d4-3197-11e6-8f50-0f956dcd2b8b.PNG)
2. Z-up (`gravity=0,0,-300`, ground plane rotation unchanged) ends up with a glitched box. ignore the background, the ground plane isn't visible here, but the box itself is partly glitched into the ground plane (blue line), which should not happen. Expected behavior would be that the box lies flat on the ground as well
   ![glitched](https://cloud.githubusercontent.com/assets/236678/16015841/ef758870-3197-11e6-8a8d-cfd132470118.PNG)
   ![glitched2](https://cloud.githubusercontent.com/assets/236678/16016140/9854f5ec-3199-11e6-9bf0-9b0fdef61d64.PNG)

Any ideas why this is and how this can be fixed?
Thanks!

**Comment by schteppe** [comment]
Really weird! But still, why such large gravity? Cannon default values were not made for that kind of gravity values.. try keeping objects around 1m large, gravity around 10m/s2 and mass around 1kg. Better?

**Comment by AtiX** [comment]
Yes, and what did the trick for me was a scaled mapping from THREE.js to cannon. Originally, size dimensions would be like 100 x 100 x 10 for the box, but scaled down to 10 x 10 x 1 yields to better, although not perfect, results. (It breaks again, however, if I change the mass of the box...)
