### ISSUE TITLE
The ball rolled down the slope, and it won't stop over time.

### ISSUE THREAD

**Issue by df257** [schteppe/cannon.js#293]
![qq](https://cloud.githubusercontent.com/assets/7835444/16221155/d39c3b9e-37c3-11e6-839e-d962017f0a04.jpg)

sphereBody.linearDamping = 0.999 or sphereBody.angularDamping = 0.999

It won't stop over time!
![qq](https://cloud.githubusercontent.com/assets/7835444/16221325/bd48b588-37c4-11e6-8c7f-7d390b6df9ce.jpg)

**Comment by schteppe** [comment]
Does that slope end at some point? The sphere won't stop in the middle of a slope no matter if you put damping on it or not. However, if it rolls on a horizontal plane it will stop after some time.

Tried both angular and linear damping recently and it worked fine...
