### ISSUE TITLE
Problem when running CANNON on Node.js

### ISSUE THREAD

**Issue by digitaledge** [schteppe/cannon.js#299]
Hello,
i am trying to run cannon with an authorative gameserver based on node.js.
On first try this looked very promising. There was no errors at all and i was able to create the world, shapes, bodies, etc. similar like i would do client side.

So my first attempt was to reproduce the pile demo server side..
Result was that the spheres did bounce right up and down with the z coord but the xy position did not update and kept the initial values.

That seems to happen only when running cannon on node.js. I did validate my code on the browser and it worked all right like in the pile demo.

There was no errors showing up on the server. 
Maybe someone has an idea what the problem could be or how to solve it?

Kind Regards
Stefan

**Comment by schteppe** [comment]
It should not behave differently in node vs browser... I've tried similar scenes server side before and got the same results as if it was in the browser.

Any idea where the problem can be? Does it still bork if you reduce it to a sphere on a plane? How does your update loop look like (there's no requestAnimationFrame in node.js for what I know).

**Comment by digitaledge** [comment]
Hey thanks for your reply.  I was going to post some example here and was surprised that it works :)
Shame on me, because the bug must be somewhere with my physics class.

Regards
Stefan

**Comment by schteppe** [comment]
Oh I see :)
