### ISSUE TITLE
intensifying bouncing - how?

### ISSUE THREAD

**Issue by makc** [schteppe/cannon.js#300]
hello there, and please halp.

I have a box jumping on the plane, with these parameters:

```
box.linearDamping = -0.5;
box.angularDamping = -0.5;
world.addContactMaterial(new CANNON.ContactMaterial(floorMaterial, boxMaterial, 0, -1.02));
```

the problem with this is that any angular velocity the box initially had eventually cancels out, except rotation around floor normal. what I want is the box to spin faster and faster after each bounce in more 'random' direction. how would I do that?

**Comment by schteppe** [comment]
Hi! How about using restitution > 1 and friction > 1 for the contact material?

Another (more controlled) approach could be to apply an impulse on the body on impact. This way it would be easier to control direction and magnitude of the new velocity/angularVelocity.

**Comment by makc** [comment]
> restitution > 1

oh thanks 😳 that was the intention, but somehow "-" sneaked in... now I need it to give just enough restitution to overcome the gravity.
