### ISSUE TITLE
On getting the local contact point

### ISSUE THREAD

**Issue by matti777** [schteppe/cannon.js#303]
I'm interested in getting the local point of collision on my shapes. I cannot find any documentation for the event parameter for 'collide' events, but after a few hours of source-diving and debugprinting I've come to the conclusion I should be looking at `event.contact.ri` / `event.contact.rj`. From the documentation for `ContactEquation` (http://schteppe.github.io/cannon.js/docs/classes/ContactEquation.html) I found similarly named parameters ri / rj, and their documentation states that "World-oriented vector that starts in body j position and goes to the contact point." which would be exactly what I need for my purposes. However when I inspect the values of ri / rj upon contact I get really absurd values: 

```
x: 1.19453453
y: -1.94233442423e-15
z: 7.7324

```

..considering the shape for that body is a Box(0.6, 0.4, 0.0001) ie. the x / z values should not be possible? Do I need to do somekind of a transform to actually get the local collision point on my Box?

thanks for cannon.js btw, I find it rather easy to use, however the documentation could sometimes be a little more in-depth for us who are not 100% familiar with physics engine concepts :P
- Matti

**Comment by matti777** [comment]
While the x coordinate could be correct, to me it seems the y value is always really close to 0 and the z value could be "anything".

**Comment by schteppe** [comment]
You get 2 points for each ContactEquation, one for each Body involved. The world contact points are:

c.bi.position + c.ri
c.bj.position + c.rj

You can use body.pointToLocalFrame() to get the corresponding local points in each body.

It looks a bit weird indeed with those values. What is the value of the other contact point? Maybe you accidentally used `.ri` instead of `.rj`? If `.bi` is your box, then you need to use `.ri`, otherwise `.rj`.

**Comment by matti777** [comment]
My box body was being .bj. So should rj be the local point (for bj) without any further transforms? Since my body has z-thickness of 0.001 I find the z value of 7.7 quite off. Also no matter where I did the collision on the box, I would get a similarly tiny (<something>e-15) y-value. And x value was being too large for my Box'es halfExtents (0.6 for x).

**Comment by matti777** [comment]
So in other words, in the following onCollision method I have: 

```
function onCollision(event) {
    if (event.contact.bj.id === boxBody.id) {
      console.log('I am bj');
      //TODO should look at event.contact.rj to find local contact point
    }
}
```

And when printing out the event.contact.rj I kept getting quite strange values.

**Comment by schteppe** [comment]
.ri and .rj are world-oriented _vectors_. So to get the local point you need to rotate them with the inverse of the corresponding body rotation. Or just use the approach I suggested above: add the body position to get the world point and then go local. I'd suggest computing the world point first to verify that you're on the right track.

**Comment by schteppe** [comment]
Btw, a thickness of 0.001 is probably too thin for a normal resting contact, and would possibly allow for tunneling. I hope you know what you're doing.

**Comment by matti777** [comment]
I am not familiar with the concept "world-oriented vector", nor did Google provide hits for it. How do you define that?
- matti

**Comment by schteppe** [comment]
A vector in world space.

.ri goes from bi.position to the contact point in world space.

See page 2 here: http://www8.cs.umu.se/kurser/5DV058/VT15/lectures/spooknotes.pdf

**Comment by matti777** [comment]
Okay I tried this now and seems I am getting proper values for the object-space collision coordinates using the pointToLocalFrame(position + r) formula. Thanks!
