### ISSUE TITLE
Issue with collision of STATIC and DYNAMIC Bodies

### ISSUE THREAD

**Issue by stuikomma** [schteppe/cannon.js#317]
I have an issue that static and dynamic bodies do not collide as they should. You can try this by making the Box in the demo [bodyTypes.html](https://github.com/schteppe/cannon.js/blob/master/demos/bodyTypes.html#L39). STATIC.

The box will no longer move up an down, which is expected behavior, since static bodies only take into account their position (as stated in the [docs](https://github.com/schteppe/cannon.js/blob/master/docs/classes/Body.html#L3000 "linking to the repo because of #316")).

However, the sphere will bounce a bit, slow down as it intersects with the box and then continue bouncing. This intersection should not happen, right?

**Comment by schteppe** [comment]
I think it bounces because the code sets the velocity of the static box... and the sphere will believe that the box below it is moving even though it is not. I guess the bouncing stops if you don't modify the velocity?

**Comment by stuikomma** [comment]
Yeah, you're right. It stops bouncing. I would expect, though, that setting a velocity on a static body wouldn't make a difference under any circumstances.

Even with setting the velocity and angularVelocity to 0 in my application, there is still an issue with static bodies. Dynamic ones simply go through them with very little force applied. I'll debug it further and let you know when I have new insights.

**Comment by schteppe** [comment]
Yeah, I guess static objects should not touch their velocity... But on the other hand, this "bug" actually lets you create conveyor belts :) try setting velocity along a horizontal axis :)

**Comment by stuikomma** [comment]
Ha, true 😃 Although that is also what kinematic bodies are for 😉

I still have my issue with changing the type. Seems that there is a difference between an object that is created static and one that is created dynamic and later set to static. I am setting the type and reset the velocity and angularVelocity to 0. Are there more properties that I should reset?

**Comment by schteppe** [comment]
To change a body into static you need to also set the mass to zero and update the mass properties.

```js
body.type = Body.STATIC;
body.mass = 0;
body.updateMassProperties();
body.aabbNeedsUpdate = true;
// ..there's probably something missing here..
```

Not sure if .updateMassProperties() is in the npm version. But in any case, the best way is just to create a new Body.

**Comment by stuikomma** [comment]
Yes, it is probably best to just create a new body. I tried it and it probably works. However, my objects are not solid, which is why the glitching happens. When one of them is static and cannot give way the two relatively thin objects will just tunnel.

Thanks for your help and I will regard this issue as solved. It might help others who want to change the body type dynamically.

Maybe we should change the title in order to reflect the subject of the discussion better.
