### ISSUE TITLE
unexpected motion for dynamic body

### ISSUE THREAD

**Issue by laurie71** [schteppe/cannon.js#326]
Expected result (code as shown below): two bodies, neither moving
Expected result (gravity not zero'd out): two bodies, on falling toward and coming to rest against the other
Actual result: body gets a large velocity in the Z direction (about 10 times the velocity along the Y direction resulting from gravity when applied after the first simulation update

I set up a super simple test to get started with Cannon, and was surprised to find my 'player proxy' body shooting off in the Z direction. The setup is about as simple as it gets:

```js
world = new cannon.World()

// world.gravity.set(0, -9.82, 0)
world.gravity.set(0, 0, 0)

let groundBody = new cannon.Body({
  position: new cannon.Vec3(0, 0, 0),
  shape: new cannon.Plane(),
  mass: 0,
})
world.addBody(groundBody)

let playerBody = new cannon.Body({
  position: new cannon.Vec3(0, 5, 0),
  shape: new cannon.Sphere(0.5),
  mass: 80,
})
world.addBody(playerBody)
```

Notice that I have gravity set to zero, the plane and the sphere are not in contact, and there are no forces applied. I drive the simulation with a simple loop:

```js
let lastUpdate
const maxSubSteps = 3
,     fixedStepSize = 1 / 60
,     fixedStepSizeMillis = fixedStepSize * 1000
function physicsLoop(tick) {
  let now = Date.now()
  ,   dt = now - (lastUpdate || now - fixedStepSizeMillis)
  ,   e = dt - fixedStepSizeMillis

  lastUpdate = now
  world.step(fixedStepSize, dt, maxSubSteps)
  // setTimeout(() => { physicsLoop(tick) }, fixedStepSizeMillis - (e > 0 ? e : 0))
  setTimeout(() => { physicsLoop(tick) }, fixedStepSizeMillis) // ^^^ is too inconsistent
}
```

Error correction on `dt` was causing too much instability so I took that out, but that turns out not to matter; `playerBody` is getting a velocity of just over 9 on Z assigned to it the first time `World.prototype.step` calls `this.internalStep(dt)`.

Where does this velocity come from? When I had gravity assigned along the Y direction I was expecting the `playerBody` to fall toward and come to rest against `groundBody`; this behaviour with gravity zero'd ou explains why that wasn't happening: if I re-enable gravity on Y the body ends up with 0.09 velocity along Y and 9+ along Z.

**Comment by schteppe** [comment]
I think the problem is because the plane shape faces in the Z direction by default, not Y. You'll have to rotate it. Something like this should do it: 

```js
groundBody.quaternion.setFromAxisAngle(new CANNON.Vec3(1,0,0),-Math.PI/2);
```

**Comment by appdlh** [comment]
Ah! So the plane orientation is not what I assumed, resulting in an initial collision state between the two bodies? That would explain it. Thanks, I'll try moving the sphere to resolve the collision to confirm.

That presents a problem, though, as I'm using cannon for server side simulation and the client side rendering framework has a different axis orientation. I'll have to figure out how to correct for that...

**Comment by laurie71** [comment]
Hmm, that's not it; I tried removing the plane altogether, so now I have a single body. It still accelerates off along Y. Is is an acceleration, too, by the way; the velocity is increasing over time.

**Comment by schteppe** [comment]
That's really weird... I'm not sure what it can be then.

I see that you pass in milliseconds as delta time. Dividing by 1000 should fix your physics update but still doesn't explain the movement :/

**Comment by laurie71** [comment]
Thanks for the tip on delta time being incorrectly scaled -- but you're right, fixing that doesn't stop the unexpected movement. It turns out you were right the first time; when I tested with the ground plane removed my editor didn't save the changes so I still had two bodies colliding. After fixing that it's all good.

Thanks for the support!
