### ISSUE TITLE
Friction not working

### ISSUE THREAD

**Issue by gregmax17** [schteppe/cannon.js#345]
In my world I have a plane and a sphere. My world has a gravity of `0, -9.82, 0`, and both bodies have a material with a friction and restitution of 0.8. 

When I apply a force to the sphere to be simulate a tossed/hit (think of a golf game, where the user chips the shot onto the green), the ball never slows down. It just keeps on rolling.

Something I'm missing?

**Comment by schteppe** [comment]
A perfect sphere will keep rolling forever even if the contact with the ground has friction. The surfaces need to have relative velocities for friction to work, and the rolling prevents this.

What you are looking for is body.linearDamping (or body.angularDamping). These will reduce the velocity (or spin) over time. Try different values larger than zero.

**Comment by gregmax17** [comment]
That works, thank you!
