### ISSUE TITLE
Player constant velocity movement without friction 

### ISSUE THREAD

**Issue by gregmax17** [schteppe/cannon.js#346]
I'm trying to move a player with a set velocity, but friction appears to be effecting it. This is what I'm trying to do: I have a dynamic sphere (my player) and a static plane in the scene, and after the `world.step` call, I set the sphere's velocity along the `x` axis to be 6. However, after the next `world.step` call the sphere's velocity along the `x` is almost cut in half to `3.054...`.

All bodies have a friction, linearDamping, and angularDamping value of `0`. So what could be causing this? How can I get my player to run at a set velocity without it being affected by friction?

**Comment by schteppe** [comment]
Sounds strange to me. Can you provide some code?

**Comment by gregmax17** [comment]
Oh. I just found out something. Its because I have my body's `fixedRotation` set to `true`. When I set it to `false` the velocity is what it should be. 

My player is actually made of 2 sphere's (to simulate a capsule), one positioned along the y at 0.5 and the other at 1.5, each with a radius of 0.5. But I have tried this with only one sphere and the unexpected behavior is still occurring. But again, when I set the `fixedRotation` to `false` it works fine, but the sphere's rotate/flip around. I can't have my player be doing that, ha.

Why is it when I set the `fixedRotation` property to `true` the velocity is cut to half?

**Comment by schteppe** [comment]
Have you seen this? https://github.com/schteppe/cannon.js/issues/218

**Comment by gregmax17** [comment]
OH... this is embarrassing. 

I set the friction, linearDamping, and angularDamping all to 0 on the bodies... but the friction is actually part of the contact material, not the body class. Oops.

It works great now.

Thank you for developing this awesome physics lib!
