### ISSUE TITLE
Cannot stack objects without sliding?

### ISSUE THREAD

**Issue by antu3199** [schteppe/cannon.js#348]
It seems to me that whenever I stack a lot of bodies together (to create a breakable wall for example), some blocks slowly start to slide off and eventually break the structure. It even happens for the jenga example in the demoes folder. If I wait long enough, the jenga tower will collapse on its own (though it takes quite a while). If I look close enough, the objects often seem to be vibrating, even for the jenga example, which is causing it to slowly collapse. Is there a parameter that I can adjust to fix this or is it a bug/limitation?

**Comment by schteppe** [comment]
Unfortunately they will always slide a tiny bit. One solution you could try is the "sleep" feature (see the [sleep demo](https://github.com/schteppe/cannon.js/blob/master/demos/sleep.html)). A slowly moving body will fall asleep, and then it won't move at all until something wakes it up.
