### ISSUE TITLE
attraction/repulsion

### ISSUE THREAD

**Issue by trusktr** [schteppe/cannon.js#362]
Can Cannon do repulsion? If not, do you know of any JS lib that does 3D attraction/repulsion

**Comment by schteppe** [comment]
You can add any force you want to your rigid bodies. Attractive or repulsive or any other force of your choice. But you will have to calculate those force yourself.

`body.force.set(x,y,z);`

Or maybe I misunderstood your question? In that case, could you explain further?

You can also use the Spring class to add an attractive force: https://github.com/schteppe/cannon.js/blob/master/demos/spring.html
