### ISSUE TITLE
Raycasting doesn't work when body.collisionResponse is set to false

### ISSUE THREAD

**Issue by TheChuckster** [schteppe/cannon.js#364]
Ray intersections are not reported by `world.raycastAll()` for bodies that have `collisionResponse` set to false. However, collision response (contact forces) are _not_ desired for some bodies that we still need to raycast. How can we disable collision response and still raycast on certain bodies?

**Comment by schteppe** [comment]
`ray.checkCollisionResponse=false;`

See the docs here: https://github.com/schteppe/cannon.js/blob/569730f94a1d9da47967a24fad0323ef7d5b4119/src/collision/Ray.js#L42

**Comment by TheChuckster** [comment]
Thanks!!! Sorry for not digging into this more first.
