### ISSUE TITLE
How do distances compare to Three.js?

### ISSUE THREAD

**Issue by TheGreatRambler** [schteppe/cannon.js#365]
I am trying to make a heightmap using element sizes that are the same as three.js. It doesn't seem to be working. Are distances in Cannon.js the same as Three.js?

**Comment by schteppe** [comment]
Hi. Yes, distances are the same. Did you try the [cannon.js debug renderer for three.js](https://github.com/schteppe/cannon.js/tree/master/tools/threejs)? It would probably help.

**Comment by radziksh** [comment]
@schteppe Nice lib 👍  works well for me 
![default](https://user-images.githubusercontent.com/1275228/37567195-63472f42-2ad4-11e8-8ec9-ed2c865e90f3.png)
