### ISSUE TITLE
laya3d

### ISSUE THREAD

**Issue by DavidHome** [schteppe/cannon.js#372]
你好，怎么在laya3d中使用connon创建一个body或者floor并且显示出来呢？

**Comment by SET001** [comment]
yes

**Comment by DavidHome** [comment]
can you help me? give me a demo?

**Comment by DavidHome** [comment]
connon.js 
Setting collision rules?
A:sphereBody.collisionfilterGroup = 1; sphereBody.collisionfilterMask = 1;
B:sphereBody.collisionfilterGroup = 2; sphereBody.collisionfilterMask = 2;

As a result, AB collided.why？how can i do？

**Comment by DavidHome** [comment]
Sprite3d.transform.rotation = body.quaternion; how can i  change body.rotation to Sprite3d.transform.rotation? thanks

**Comment by johnnysuen** [comment]
body.quaternion.copy(quat)就行了，或者单个分量赋值，分别设置 xyzw

**Comment by schteppe** [comment]
You can’t assign a cannon.js quaternion directly to an object in another library and expect it to work. Instead, copy it’s values. The following should work for most libraries:

```js
otherQuaternion.x = body.quaternion.x;
otherQuaternion.y = body.quaternion.y;
otherQuaternion.z = body.quaternion.z;
otherQuaternion.w = body.quaternion.w;
```

In cannon.js, it’s also possible to do the reverse, if you want to copy rotations from another library into cannon:

```js
body.quaternion.x = ...;
body.quaternion.y = ...;
body.quaternion.z = ...;
body.quaternion.w = ...;
```
How to read or write from Laya3d rotations is a different question, ask the library owner.

**Comment by DavidHome** [comment]
thank you for reply！ 
  i known how to do it。thank you very much！







------------------ 原始邮件 ------------------
发件人: "Stefan Hedman"<notifications@github.com>;
发送时间: 2018年6月26日(星期二) 下午2:23
收件人: "schteppe/cannon.js"<cannon.js@noreply.github.com>;
抄送: "大伟"<373303462@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [schteppe/cannon.js] laya3d (#372)




You can’t assign a cannon.js quaternion directly to an object in another library and expect it to work. Instead, copy it’s values. The following should work for most libraries:
 otherQuaternion.x = body.quaternion.x; otherQuaternion.y = body.quaternion.y; otherQuaternion.z = body.quaternion.z; otherQuaternion.w = body.quaternion.w;
 
In cannon.js, it’s also possible to do the reverse, if you want to copy rotations from another library into cannon:
 body.quaternion.x = ...; body.quaternion.y = ...; body.quaternion.z = ...; body.quaternion.w = ...;
 
How to read or write from Laya3d rotations is a different question, ask the library owner.
