### ISSUE TITLE
Body.collisionFilterMask default value is -1 in Body constructor, but 1 in the built bundle file.

### ISSUE THREAD

**Issue by jimtang** [schteppe/cannon.js#399]
Guess -1(0xFFFFFFFF) is correct, suggest re-pack the bundle file and update the npm module. Thanks.

**Comment by swift502** [comment]
I was also very confused by this in #387. The build as well as the npm module are apparently outdated by about 3 years. And I don't think it's about to change any time soon.

![image](https://user-images.githubusercontent.com/24359130/46397044-6d6bcf00-c6f1-11e8-8535-1860b4a02ed9.png)

Documentation is also incredibly out of date and missing essential features. It can be quite confusing before you realise what's happening.

Right now, just don't use the official build. Build Cannon yourself locally and use that version. If you publish an app, ship your build of Cannon with it.

**Comment by jimtang** [comment]
Oh, got that, and it's sad to know Cannon is not developing anymore...

**Comment by swift502** [comment]
I know, but so far I found everything I needed in Cannon. There's lacking support for some collision pairs (box to trimesh), but I think it's quite a great engine as is, and when I need those features, it should be possible to implement them myself.

3D Physics in a browser just seems like a very niche thing right now with not many people using it. Looking at the [network graph](https://github.com/schteppe/cannon.js/network), only one person seems to be actively updating cannon.

And then there's Ammo.js, the popularity of which I don't understand. I failed to do basic things with it, but it seems to be somewhat maintained.

I'd personally love to help with maintaining Cannon but my knowledge about how it works is very surface-level...

**Comment by dirkk0** [comment]
I am also very fond of Cannon, and I don't think @schteppe gave up on it - he might just not have the time now.
Maybe you could co-maintain it? Simply checking in the latest build is useful per se, and someone beefing up the docs would be useful, too.

**Comment by swift502** [comment]
I'll be happy to keep submitting PR's when I add new features to my fork and hope they get merged one day, but I think that's about all we can do now...

**Comment by robrohan** [comment]
I also like using cannon and have forked it and ported it to typescript (minus trimesh, and a few odd bugs).  I’ll be using it for the near future.  Happy to help if people want to start a movement :)

**Comment by swift502** [comment]
@robrohan Wow, that's really cool...
What's the reason behind leaving trimesh behind? If you had sphere to trimesh and raycasting against trimesh, I might want to jump over to your fork. It'd be cool to have an alive version of cannon and share features.

Edit: 
![image](https://user-images.githubusercontent.com/24359130/47113344-099ce680-d259-11e8-8f8a-93148150f0e2.png)
lol 🙂

**Comment by robrohan** [comment]
@swift502 no reason other than I don’t need it yet and I was trying to limit the code for the port (less to try to debug).  The code is still there just commented out for now.  I’ve run into issues #109 and have started trying to sort that out.  I think I’ll have to refactor convex vs convex as its difficult to reason about atm.  

Here is the engine so far http://mesh.robrohan.com/#level:movement but it’s not open source.

**Comment by swift502** [comment]
@robrohan I'll definitely look into it. If I end up using Dapao I might try to port the trimesh stuff over myself when I need it (and if you allowed it of course... 🙂).

And your engine looks great, I already played it and watched your update videos...
