### ISSUE TITLE
Ability to specify dimensions of CANNON.Plane()

### ISSUE THREAD

**Issue by nickmcmillan** [schteppe/cannon.js#403]
I'm creating a solid ground/floor with;
```
const shape = new CANNON.Plane()
const body = new CANNON.Body({ mass: 0, shape })
...
```

The size of this plane seems to be infinite. 
My question is whether it's possible to configure it's dimensions, perhaps similar to how we create a plane in Three; for example; `new THREE.PlaneGeometry(10, 10)`

Ideally I'd like to define the planes' dimensions so I can have Cannon bodies fall off the edge.

**Comment by Zbluu** [comment]
It's a bit tricky, but you can do it by using and generate your own trimesh with 2 triangles to form a square.

**Comment by schteppe** [comment]
@Zbluu is right. I’d recommend using a box shape though. Adding some depth to your “plane” will make it more difficult to clip through for high velocity objects.

The Plane class is really a plane in the “math speak” sense - it doesn’t have limits...

**Comment by nickmcmillan** [comment]
Fantastic thanks for the answers @Zbluu & @schteppe. Changing the Plane to a Box did the trick;
`const shape = new CANNON.Box(new CANNON.Vec3(10, 10, 0.1))`
