### ISSUE TITLE
Objects falling through each other but with resistance

### ISSUE THREAD

**Issue by davidpuetter** [schteppe/cannon.js#405]
Hi, 

I have two meshes in Three.js that I'm giving bodies to. I'm The syncing works perfectly fine however the collisions seem funky. 
Box1 is my floor, about 1 unit high, 9 units wide and 9 units deep. Created as a Body.STATIC.
Box2 is a cube, 1 x 1 x 1, created as BODY.DYNAMIC with Mass of 1.0.

Dropping Box2 from a height of about 10 makes it fall down naturally but as soon as it hits the floor, it slows down and "eases" its way through the box until it comes out the other side and shoots out. 
   
[Video](http://davidpuetter.com/u/%25pn-2018-11-07_00-09-51.mp4)

I tried setting the floor to Body.KINEMATIC and the collisions worked perfectly fine however the floor moves continuously in circles (which is probably a whole different issue)

[Video 2](https://drive.google.com/uc?id=1ucCJDMHqAU8Px2EiFGx71CxeIb0oSmvU)
(Nothing is altering their rotations/position. They're only syncing using `this.mesh.position.copy(this.body.position);` and `this.mesh.quaternion.copy(this.body.quaternion);`)

Is there something wrong with my world setup? My gravity is set up as (0, -9.82, 0), broadphase is NaiveBroadphase, solver.iterations is set to 10.

**Comment by schteppe** [comment]
Can’t see anything obviously wrong with your demo. All sounds fine... Can you provide more code? What other settings do you provide to cannon?

**Comment by davidpuetter** [comment]
I can't provide a full demo right now sadly but I'll see if I can hack together a small one later! The gist of the application though is that I import data from a map editor, create THREE meshes based from that data and give them a cannon body and shape with that data too. The Cannon/THREE debug renderer shows all the shapes correctly... just collisions that are funky. 

I'll update later on in the day with a demo!

**Comment by davidpuetter** [comment]
Hey @schteppe, so sorry for the delay! I had to remove a ton of stuff because a lot of it is still private. Even with this simplified example, the issue(s) persist. 
  
A build is here: http://davidpuetter.com/games/cannontest/
And the source: https://github.com/davidpox/cannon-test

**Comment by davidpuetter** [comment]
All good, I found the issue. If I set the mass of the static object to anything non-zero, it breaks.
