### ISSUE TITLE
RaycastVehicle wheel collision issue + improvement

### ISSUE THREAD

**Issue by tomo0613** [schteppe/cannon.js#413]
Greetings

I have this project
https://github.com/tomo0613/offroadJS (DEMO link in the readme)

I'm pretty happy with the physics so far, but i would like to add some platforms to the world.
* My issue is:
 Looks like if I add a box that is not under the vehicle at start, it wont be detectable by the rays of the wheels. (I couldn't sort it out, what is happening)

\+
* I found this video [Single raycast vs. Multi raycast vehicle wheels - Unreal Engine 4](https://www.youtube.com/watch?v=RAwejRR63Zc)  (comments are interesting as well)

Sadly i have no idea about the math.
It would be nice if some could implement it, in the lib.

**Comment by dlannan** [comment]
Hi. I have done something different for my solution. Its a little crazy, but results in extremely accurate raycast lookups and it can do hundreds/thousands lookups in a frame.
I simply render an ortho depth camera shader from the cars position + some height (I choose 5m). The depth buffer then has an accurate vertical distance that your suspension can travel. I also point the render in the direction of the car body local "down" axis.
You can then sample a simple depth "array" of vertical heights for each wheel 'area'. So you can even simulate different sized 'grip' areas for each tyre... its quite nice (lots of complex things can be done).

**Comment by tomo0613** [comment]
Interesting idea, regardless i do not understand it. :/
[this article](https://chrismflynn.wordpress.com/2012/09/06/fun-with-shaders-and-the-depth-buffer/) looked relevant, but I still don't get it.
It would have been great if you had an example. Thank you anyway. :)

As I understand, your solution would not not use the RaycastVehicle from the physics lib, and instead of rays, it would use an OrthographicCamera that looks down the car, the wheels should have a CylinderBufferGeometry and a special "depth" Shader, then the suspension, friction, etc. has to be implemented.
Is this near to your idea?

Current issue happens when the wheel reaches the grey rectangle
![wheel-contact](https://user-images.githubusercontent.com/18551999/66260951-c5865700-e7c5-11e9-807c-abf8e14f41dc.png)

**Comment by dlannan** [comment]
This is effectively what I do. For best results you need to have near and far camera far enough apart to capture the obstacles you want too (can actually do a reasonable job at walls and posts). 
I actually use the normal RaycastVehicle with my own inserted raycast callback. I manage the "responses" in there and it seems to work very well. 
Currently theres a couple of minor issues:
- Any tiny little gap in the geometry will give you a "hole" in the road .. can be annoying to fix.
- The depth render is really only supported on desktop/pc systems so I use a normal raycast for mobile (makes it a little slow). I expect to fix this later with my own mobile shader for this.
The shader and update mechanics are the biggest pain, you need to carefully sync the physics for the rendering, not the render frame. 
Heres a snippet of my raycast function
var customRayCaster = function(from, to, result ) {

    // No movement if physics isnt ready
    if(mappedChannels[0].depthIsReady == false) return;

    var pos = from;
    var py = pos.y;

    //trigger your events. 
    var cam = mappedChannels[0];
    
    var cpos = Physics.chassisMesh.position; //cam.depthCamera.position;
    var rpos = { x: cpos.x - pos.x, y: cpos.y - pos.y, z: cpos.z - pos.z };
  
    // Using depth buffer .. lookup wheel!!
    var buff = cam.depthBuffer;
    var centerxy = cam.depthResolution / 2;

// Sample the depth buffer for where to look for your wheels
//   Note: TURN OFF LOGARITHMIC DEPTH BUFFER!!  I dont know how to extract that yet.

   // This normalises the height relative to the world
    var height  = cam.depthCamera.position.y - (1.0 - buff[lu]) * cam.depthDeep;

    var hitSpot = new CANNON.Vec3(pos.x, height, pos.z);
    var dist = hitSpot.distanceTo(from);
    var fullDistance = from.distanceTo(to);

    // Large values mean no hit!
    if(buff[lu] > 0.95) {
        result.distance = -1;
        result.hasHit = false;
        result.body = null;
        return false;
    }

    result.hitPointWorld = hitSpot;
    result.hitNormalWorld = norm;
    result.distance = dist;
    result.hasHit = true;
    result._shouldStop = true;

    // This just ensures that our data is read!!
    result.body = Physics.ground;
    return true;
}
Hope that helps. You will need to make your own depth buffer (threejs has one) and render it in the right spot at the right time :)

**Comment by tomo0613** [comment]
looks like setting `aabbNeedsUpdate = true;` on bodies, solves the issue.
