### ISSUE TITLE
Error in Quaternion Rotation

### ISSUE THREAD

**Issue by samuelbelolo** [schteppe/cannon.js#445]
Hey there, 
First of all thanks a lot for this amazing Physics Engine.

Let's introduce what i want to do. I am currently using Cannon along with ThreeJS.
I am importing geometry, calc the dimensions of the three object.Then creating the Cannon Box.  But i cant figure why the Cannon Body has a bad rotation when i pass it the original element.quaternion. 

```
const createCannonBoxFromObject = (elem) => {
    const mass = 0
    const boundary = new THREE.Box3().setFromObject(elem)
    const size = boundary.getSize()

    const box = new CANNON.Box(new CANNON.Vec3().copy(size).scale(0.5))
    const body = new CANNON.Body({
        mass: mass,
        position: new CANNON.Vec3(elem.position.x ,elem.position.y , elem.position.z ),
        quaternion : new CANNON.Quaternion(elem.quaternion.x,elem.quaternion.y, elem.quaternion.z, elem.quaternion.w)
    })
}
```

See : in Red the cannon element with the cannon debug tool

<img width="500" alt="Capture d’écran 2020-05-08 à 04 34 21" src="https://user-images.githubusercontent.com/32864353/81364141-3e93b700-90e5-11ea-9470-111fa808131f.png">

Do you see another good way to do it ? Do i got something wrong ? 

Many thanks in advance

**Comment by d3x0r** [comment]
it doesn't look wrong to me... just a matter of perspective - literally.

**Comment by Dannie226** [comment]
It seems you never actually set the shape of the body to be the box. You made the CANNON.Box, but in the CANNON.Body, you should set the shape to the CANNON.Box.

**Comment by samuelbelolo** [comment]
Indeed ! Old issue, cleaning it all the way
