### ISSUE TITLE
Normal of collided face

### ISSUE THREAD

**Issue by trevex** [schteppe/cannon.js#52]
We are currently using cannon.js along with three.js for a university project. The level has a lot of static objects that were blocked out by the level designer as well. This cuboid mesh is then used to create physics cubes representing them. 
Everything works fine, but I have an issue getting the jumping to work properly. The jumping is basically a flag being set whenever the player hits the ground to allow the player to jump.

The problem: Whenever the player hits something it gets reseted, which means the player can jump up big objects by constantly jumping against the wall and keep jumping. Although it is a lot of fun it is not the intended behaviour.

There is a lot of information contained in the collision event, but I could get it to work properly. 

The question: How do I calculate the normal of the face/plane/side what a object collided with?

Thanks for the brilliant work and your compound objects was something I was looking forward to a long time :)

**Comment by DelvarWorld** [comment]
How can I get this data in the `beginContact` event?
