### ISSUE TITLE
Cylinder cannon.js vs cylinder three.js 

### ISSUE THREAD

**Issue by mdrorum** [schteppe/cannon.js#58]
Hello, I would like to thank the cannon.js author for this fantastic library.

I have a problem with the cylinder geometry. Other elements, such as cube or sphere work well.

The problem is the difference in orientation between the cylinders libraries.

Three.js constructed with the main cylinder axis vertical, but cannon.js it builds with the horizontal axis.

I tried playing with quaternions for change orientation, but I could not see the mesh in cannon.js.

Try it at: http://www.m500.es/webgl/_cilindro_01.html

Here's the code:

http://www.m500.es/webgl/_cilindro_01.txt

![cilindro cannon three](https://f.cloud.github.com/assets/2923928/214134/c951646a-83f4-11e2-9999-3de2571fecae.jpg)

**Comment by tommhuth** [comment]
I'm having the same problem, but this solution does not work for me. Is this answer now out of date? If so, what would be the way about it now? If I do:

```js
quat.setFromAxisAngle(new Vec3(-1, 0, 0), -Math.PI / 2)
```
it looks like it works at least for an even number of sides?

**Comment by schteppe** [comment]
Sounds weird! Did you try building cannon.js locally and using the most recent version?

Which solution are you trying? Transforming all points or setting the local shape transform?

(There is one more solution to this problem: put your three js mesh object into an empty THREE.Object3d. Set the local rotation of the mesh to fix the orientation. During runtime, apply cannon.js transform on the parent.)

**Comment by tommhuth** [comment]
So I can confirm that (using local shape transform)

```js
quat.setFromAxisAngle(new CANNON.Vec3(1,0,0),-Math.PI/2);
```

does work, but not for a cylinder with 5 or 6 sides where the sides seems to be offset. 4, 8 and 12 all work fine.

**Comment by tommhuth** [comment]
I'm using version 0.6.2, which I just realize was released three years ago (!). Is the NPM package not maintained anymore?

**Comment by kelvinkoko** [comment]
I seems can't find `transformAllPoints` in Doc and npm's version. Will it be included in the library?

**Comment by sunwin123** [comment]
I am using the 0.6.2 version.
The following is what I do, it works fine:

>      var geoCylinder = new THREE.CylinderGeometry(1,1,1,8);
>      geoCylinder.rotateX(Math.PI/2);
>      var matCylinder = new THREE.MeshPhongMaterial({color:0x009999});
>      var cylinder = new THREE.Mesh(geoCylinder, matCylinder);
>      scene.add(cylinder);

The key is rotateX(90 degree) to the three.js' cylinder geometry, which will correct and adapt it to cannon.js' cylinder shape:
> geoCylinder.rotateX(Math.PI/2);

The test screen record:
![46rxCmyPOU](https://user-images.githubusercontent.com/9605879/80068957-13508a00-8573-11ea-8ba1-ccd801beca11.gif)

**Comment by Untimely83** [comment]
> Hello and thanks for using the lib!
> 
> There are a couple of ways of changing the cylinder orientation so it matches Three.js. The most performant way would probably be to transform all the points in the polyhedron (yes, the Cylinder is in fact a subclass of ConvexPolyhedron). You do this by using the method ConvexPolyhedron.transformAllPoints(translation,quaternion).
> 
> To rotate the points so the cylinder Z axis is is aligned with the Y axis instead, do something like this (you can run this code in the JS console while your app is running):
> 
> ```
> var cylinderBody = world.bodies[1];
> var quat = new CANNON.Quaternion();
> quat.setFromAxisAngle(new CANNON.Vec3(1,0,0),-Math.PI/2);
> var translation = new CANNON.Vec3(0,0,0);
> cylinderBody.shape.transformAllPoints(translation,quat);
> ```
> 
> This rotates all shape points 90 degrees around the local X axis, and the RigidBody quaternion should now match your mesh quaternion.
> 
> The other solution would be to put the cylinder shape inside a Compound shape, with the same transform parameters. This would lead to worse performance in the nearphase though.
> 
> Good luck with your app! If you plan to release a game or some other interesting software you want us to see, [add your project to the wiki](https://github.com/schteppe/cannon.js/wiki/Projects-using-Cannon.js). Thanks.
> 
> Stefan





https://stackdev.space/questions/create-a-solid-cylindergeometry-without-any-hollow-parts
